--This file is generated by tools!
--Please do not modify this file!
module("tableData_tTalentCategory",package.seeall)
data = {


		[1] = { 

			id = 1,
			UnlockCondition = "",
			Icon = "Icon_TalCat_1",
			Name = "Tal_1_cat",
		},
		[2] = { 

			id = 2,
			UnlockCondition = "",
			Icon = "Icon_TalCat_2",
			Name = "Tal_2_cat",
		},
}
Count=2
