--This file is generated by tools!
--Please do not modify this file!
module("tableData_tClimbCondition",package.seeall)
data = {


		[10101] = { 

			id = 10101,
			type = 1,
			arg1 = 5,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10102] = { 

			id = 10102,
			type = 2,
			arg1 = 1,
			arg2 = 10,
			arg3 = 0,
			description = "star_115_des",
		},
		[10103] = { 

			id = 10103,
			type = 2,
			arg1 = 21,
			arg2 = 10,
			arg3 = 0,
			description = "star_115_des",
		},
		[10201] = { 

			id = 10201,
			type = 1,
			arg1 = 10,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10202] = { 

			id = 10202,
			type = 2,
			arg1 = 1,
			arg2 = 10,
			arg3 = 0,
			description = "star_115_des",
		},
		[10203] = { 

			id = 10203,
			type = 2,
			arg1 = 6,
			arg2 = 10,
			arg3 = 0,
			description = "star_115_des",
		},
		[10301] = { 

			id = 10301,
			type = 1,
			arg1 = 15,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10302] = { 

			id = 10302,
			type = 2,
			arg1 = 1,
			arg2 = 10,
			arg3 = 0,
			description = "star_115_des",
		},
		[10303] = { 

			id = 10303,
			type = 2,
			arg1 = 4,
			arg2 = 10,
			arg3 = 0,
			description = "star_115_des",
		},
		[10401] = { 

			id = 10401,
			type = 1,
			arg1 = 20,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10402] = { 

			id = 10402,
			type = 2,
			arg1 = 1,
			arg2 = 10,
			arg3 = 0,
			description = "star_115_des",
		},
		[10403] = { 

			id = 10403,
			type = 2,
			arg1 = 22,
			arg2 = 10,
			arg3 = 0,
			description = "star_115_des",
		},
		[10501] = { 

			id = 10501,
			type = 1,
			arg1 = 25,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10502] = { 

			id = 10502,
			type = 2,
			arg1 = 1,
			arg2 = 12,
			arg3 = 0,
			description = "star_115_des",
		},
		[10503] = { 

			id = 10503,
			type = 2,
			arg1 = 11,
			arg2 = 12,
			arg3 = 0,
			description = "star_115_des",
		},
		[10601] = { 

			id = 10601,
			type = 1,
			arg1 = 30,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10602] = { 

			id = 10602,
			type = 2,
			arg1 = 1,
			arg2 = 12,
			arg3 = 0,
			description = "star_115_des",
		},
		[10603] = { 

			id = 10603,
			type = 2,
			arg1 = 12,
			arg2 = 12,
			arg3 = 0,
			description = "star_115_des",
		},
		[10701] = { 

			id = 10701,
			type = 1,
			arg1 = 35,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10702] = { 

			id = 10702,
			type = 2,
			arg1 = 1,
			arg2 = 12,
			arg3 = 0,
			description = "star_115_des",
		},
		[10703] = { 

			id = 10703,
			type = 2,
			arg1 = 24,
			arg2 = 12,
			arg3 = 0,
			description = "star_115_des",
		},
		[10801] = { 

			id = 10801,
			type = 1,
			arg1 = 40,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10802] = { 

			id = 10802,
			type = 2,
			arg1 = 1,
			arg2 = 13,
			arg3 = 0,
			description = "star_115_des",
		},
		[10803] = { 

			id = 10803,
			type = 2,
			arg1 = 6,
			arg2 = 13,
			arg3 = 0,
			description = "star_115_des",
		},
		[10901] = { 

			id = 10901,
			type = 1,
			arg1 = 45,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[10902] = { 

			id = 10902,
			type = 2,
			arg1 = 1,
			arg2 = 13,
			arg3 = 0,
			description = "star_115_des",
		},
		[10903] = { 

			id = 10903,
			type = 2,
			arg1 = 23,
			arg2 = 13,
			arg3 = 0,
			description = "star_115_des",
		},
		[11001] = { 

			id = 11001,
			type = 1,
			arg1 = 50,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11002] = { 

			id = 11002,
			type = 2,
			arg1 = 1,
			arg2 = 14,
			arg3 = 0,
			description = "star_115_des",
		},
		[11003] = { 

			id = 11003,
			type = 2,
			arg1 = 4,
			arg2 = 14,
			arg3 = 0,
			description = "star_115_des",
		},
		[11101] = { 

			id = 11101,
			type = 1,
			arg1 = 55,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11102] = { 

			id = 11102,
			type = 2,
			arg1 = 1,
			arg2 = 14,
			arg3 = 0,
			description = "star_115_des",
		},
		[11103] = { 

			id = 11103,
			type = 6,
			arg1 = 100000,
			arg2 = 0,
			arg3 = 0,
			description = "star_119_des",
		},
		[11201] = { 

			id = 11201,
			type = 1,
			arg1 = 60,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11202] = { 

			id = 11202,
			type = 2,
			arg1 = 1,
			arg2 = 14,
			arg3 = 0,
			description = "star_115_des",
		},
		[11203] = { 

			id = 11203,
			type = 5,
			arg1 = 3,
			arg2 = 40,
			arg3 = 0,
			description = "star_118_des",
		},
		[11301] = { 

			id = 11301,
			type = 1,
			arg1 = 65,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11302] = { 

			id = 11302,
			type = 2,
			arg1 = 1,
			arg2 = 15,
			arg3 = 0,
			description = "star_115_des",
		},
		[11303] = { 

			id = 11303,
			type = 2,
			arg1 = 4,
			arg2 = 15,
			arg3 = 0,
			description = "star_115_des",
		},
		[11401] = { 

			id = 11401,
			type = 1,
			arg1 = 70,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11402] = { 

			id = 11402,
			type = 2,
			arg1 = 1,
			arg2 = 15,
			arg3 = 0,
			description = "star_115_des",
		},
		[11403] = { 

			id = 11403,
			type = 2,
			arg1 = 13,
			arg2 = 15,
			arg3 = 0,
			description = "star_115_des",
		},
		[11501] = { 

			id = 11501,
			type = 1,
			arg1 = 75,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11502] = { 

			id = 11502,
			type = 2,
			arg1 = 1,
			arg2 = 16,
			arg3 = 0,
			description = "star_115_des",
		},
		[11503] = { 

			id = 11503,
			type = 2,
			arg1 = 14,
			arg2 = 15,
			arg3 = 0,
			description = "star_115_des",
		},
		[11601] = { 

			id = 11601,
			type = 1,
			arg1 = 80,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11602] = { 

			id = 11602,
			type = 2,
			arg1 = 1,
			arg2 = 16,
			arg3 = 0,
			description = "star_115_des",
		},
		[11603] = { 

			id = 11603,
			type = 2,
			arg1 = 43,
			arg2 = 15,
			arg3 = 0,
			description = "star_115_des",
		},
		[11701] = { 

			id = 11701,
			type = 1,
			arg1 = 85,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11702] = { 

			id = 11702,
			type = 2,
			arg1 = 1,
			arg2 = 16,
			arg3 = 0,
			description = "star_115_des",
		},
		[11703] = { 

			id = 11703,
			type = 2,
			arg1 = 5,
			arg2 = 15,
			arg3 = 0,
			description = "star_115_des",
		},
		[11801] = { 

			id = 11801,
			type = 1,
			arg1 = 90,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11802] = { 

			id = 11802,
			type = 2,
			arg1 = 1,
			arg2 = 17,
			arg3 = 0,
			description = "star_115_des",
		},
		[11803] = { 

			id = 11803,
			type = 9,
			arg1 = 3500,
			arg2 = 2,
			arg3 = 1004,
			description = "star_122_des",
		},
		[11901] = { 

			id = 11901,
			type = 1,
			arg1 = 95,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[11902] = { 

			id = 11902,
			type = 2,
			arg1 = 1,
			arg2 = 17,
			arg3 = 0,
			description = "star_115_des",
		},
		[11903] = { 

			id = 11903,
			type = 2,
			arg1 = 5,
			arg2 = 17,
			arg3 = 0,
			description = "star_115_des",
		},
		[12001] = { 

			id = 12001,
			type = 1,
			arg1 = 100,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12002] = { 

			id = 12002,
			type = 2,
			arg1 = 1,
			arg2 = 17,
			arg3 = 0,
			description = "star_115_des",
		},
		[12003] = { 

			id = 12003,
			type = 2,
			arg1 = 22,
			arg2 = 16,
			arg3 = 0,
			description = "star_115_des",
		},
		[12101] = { 

			id = 12101,
			type = 1,
			arg1 = 105,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12102] = { 

			id = 12102,
			type = 2,
			arg1 = 1,
			arg2 = 18,
			arg3 = 0,
			description = "star_115_des",
		},
		[12103] = { 

			id = 12103,
			type = 2,
			arg1 = 24,
			arg2 = 18,
			arg3 = 0,
			description = "star_115_des",
		},
		[12201] = { 

			id = 12201,
			type = 1,
			arg1 = 110,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12202] = { 

			id = 12202,
			type = 2,
			arg1 = 1,
			arg2 = 18,
			arg3 = 0,
			description = "star_115_des",
		},
		[12203] = { 

			id = 12203,
			type = 2,
			arg1 = 6,
			arg2 = 18,
			arg3 = 0,
			description = "star_115_des",
		},
		[12301] = { 

			id = 12301,
			type = 1,
			arg1 = 115,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12302] = { 

			id = 12302,
			type = 2,
			arg1 = 1,
			arg2 = 18,
			arg3 = 0,
			description = "star_115_des",
		},
		[12303] = { 

			id = 12303,
			type = 5,
			arg1 = 4,
			arg2 = 60,
			arg3 = 0,
			description = "star_118_des",
		},
		[12401] = { 

			id = 12401,
			type = 1,
			arg1 = 120,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12402] = { 

			id = 12402,
			type = 2,
			arg1 = 1,
			arg2 = 19,
			arg3 = 0,
			description = "star_115_des",
		},
		[12403] = { 

			id = 12403,
			type = 6,
			arg1 = 250000,
			arg2 = 0,
			arg3 = 0,
			description = "star_119_des",
		},
		[12501] = { 

			id = 12501,
			type = 1,
			arg1 = 125,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12502] = { 

			id = 12502,
			type = 2,
			arg1 = 1,
			arg2 = 19,
			arg3 = 0,
			description = "star_115_des",
		},
		[12503] = { 

			id = 12503,
			type = 7,
			arg1 = 10000,
			arg2 = 3,
			arg3 = 0,
			description = "star_120_des",
		},
		[12601] = { 

			id = 12601,
			type = 1,
			arg1 = 130,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12602] = { 

			id = 12602,
			type = 2,
			arg1 = 1,
			arg2 = 20,
			arg3 = 0,
			description = "star_115_des",
		},
		[12603] = { 

			id = 12603,
			type = 2,
			arg1 = 11,
			arg2 = 19,
			arg3 = 0,
			description = "star_115_des",
		},
		[12701] = { 

			id = 12701,
			type = 1,
			arg1 = 135,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12702] = { 

			id = 12702,
			type = 2,
			arg1 = 1,
			arg2 = 20,
			arg3 = 0,
			description = "star_115_des",
		},
		[12703] = { 

			id = 12703,
			type = 2,
			arg1 = 21,
			arg2 = 20,
			arg3 = 0,
			description = "star_115_des",
		},
		[12801] = { 

			id = 12801,
			type = 1,
			arg1 = 140,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12802] = { 

			id = 12802,
			type = 2,
			arg1 = 1,
			arg2 = 20,
			arg3 = 0,
			description = "star_115_des",
		},
		[12803] = { 

			id = 12803,
			type = 2,
			arg1 = 23,
			arg2 = 20,
			arg3 = 0,
			description = "star_115_des",
		},
		[12901] = { 

			id = 12901,
			type = 1,
			arg1 = 145,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[12902] = { 

			id = 12902,
			type = 2,
			arg1 = 1,
			arg2 = 21,
			arg3 = 0,
			description = "star_115_des",
		},
		[12903] = { 

			id = 12903,
			type = 2,
			arg1 = 6,
			arg2 = 20,
			arg3 = 0,
			description = "star_115_des",
		},
		[13001] = { 

			id = 13001,
			type = 1,
			arg1 = 150,
			arg2 = 0,
			arg3 = 0,
			description = "star_114_des",
		},
		[13002] = { 

			id = 13002,
			type = 2,
			arg1 = 1,
			arg2 = 22,
			arg3 = 0,
			description = "star_115_des",
		},
		[13003] = { 

			id = 13003,
			type = 2,
			arg1 = 4,
			arg2 = 22,
			arg3 = 0,
			description = "star_115_des",
		},
}
Count=90
