--This file is generated by tools!
--Please do not modify this file!
module("tableData_tUnionBadgeBorder",package.seeall)
data = {


		[1] = { 

			id = 1,
			icon = "bottom1",
		},
		[2] = { 

			id = 2,
			icon = "bottom2",
		},
		[3] = { 

			id = 3,
			icon = "bottom3",
		},
		[4] = { 

			id = 4,
			icon = "bottom4",
		},
		[5] = { 

			id = 5,
			icon = "bottom5",
		},
		[6] = { 

			id = 6,
			icon = "bottom6",
		},
		[7] = { 

			id = 7,
			icon = "bottom7",
		},
}
Count=7
