--This file is generated by tools!
--Please do not modify this file!
module("tableData_tHeroExp",package.seeall)
data = {


		[1] = { 

			id = 1,
			exp = 100,
			levelExp = 100,
		},
		[2] = { 

			id = 2,
			exp = 285,
			levelExp = 185,
		},
		[3] = { 

			id = 3,
			exp = 565,
			levelExp = 280,
		},
		[4] = { 

			id = 4,
			exp = 965,
			levelExp = 400,
		},
		[5] = { 

			id = 5,
			exp = 1504,
			levelExp = 539,
		},
		[6] = { 

			id = 6,
			exp = 2104,
			levelExp = 600,
		},
		[7] = { 

			id = 7,
			exp = 2764,
			levelExp = 660,
		},
		[8] = { 

			id = 8,
			exp = 3606,
			levelExp = 842,
		},
		[9] = { 

			id = 9,
			exp = 4606,
			levelExp = 1000,
		},
		[10] = { 

			id = 10,
			exp = 5806,
			levelExp = 1200,
		},
		[11] = { 

			id = 11,
			exp = 7111,
			levelExp = 1305,
		},
		[12] = { 

			id = 12,
			exp = 8521,
			levelExp = 1410,
		},
		[13] = { 

			id = 13,
			exp = 10036,
			levelExp = 1515,
		},
		[14] = { 

			id = 14,
			exp = 11656,
			levelExp = 1620,
		},
		[15] = { 

			id = 15,
			exp = 13381,
			levelExp = 1725,
		},
		[16] = { 

			id = 16,
			exp = 15211,
			levelExp = 1830,
		},
		[17] = { 

			id = 17,
			exp = 17146,
			levelExp = 1935,
		},
		[18] = { 

			id = 18,
			exp = 19186,
			levelExp = 2040,
		},
		[19] = { 

			id = 19,
			exp = 21331,
			levelExp = 2145,
		},
		[20] = { 

			id = 20,
			exp = 23731,
			levelExp = 2400,
		},
		[21] = { 

			id = 21,
			exp = 26581,
			levelExp = 2850,
		},
		[22] = { 

			id = 22,
			exp = 29931,
			levelExp = 3350,
		},
		[23] = { 

			id = 23,
			exp = 33731,
			levelExp = 3800,
		},
		[24] = { 

			id = 24,
			exp = 38031,
			levelExp = 4300,
		},
		[25] = { 

			id = 25,
			exp = 42781,
			levelExp = 4750,
		},
		[26] = { 

			id = 26,
			exp = 47981,
			levelExp = 5200,
		},
		[27] = { 

			id = 27,
			exp = 54431,
			levelExp = 6450,
		},
		[28] = { 

			id = 28,
			exp = 61731,
			levelExp = 7300,
		},
		[29] = { 

			id = 29,
			exp = 69881,
			levelExp = 8150,
		},
		[30] = { 

			id = 30,
			exp = 78881,
			levelExp = 9000,
		},
		[31] = { 

			id = 31,
			exp = 88641,
			levelExp = 9760,
		},
		[32] = { 

			id = 32,
			exp = 99161,
			levelExp = 10520,
		},
		[33] = { 

			id = 33,
			exp = 110441,
			levelExp = 11280,
		},
		[34] = { 

			id = 34,
			exp = 122481,
			levelExp = 12040,
		},
		[35] = { 

			id = 35,
			exp = 135281,
			levelExp = 12800,
		},
		[36] = { 

			id = 36,
			exp = 149811,
			levelExp = 14530,
		},
		[37] = { 

			id = 37,
			exp = 166071,
			levelExp = 16260,
		},
		[38] = { 

			id = 38,
			exp = 184061,
			levelExp = 17990,
		},
		[39] = { 

			id = 39,
			exp = 203781,
			levelExp = 19720,
		},
		[40] = { 

			id = 40,
			exp = 225231,
			levelExp = 21450,
		},
		[41] = { 

			id = 41,
			exp = 248051,
			levelExp = 22820,
		},
		[42] = { 

			id = 42,
			exp = 272241,
			levelExp = 24190,
		},
		[43] = { 

			id = 43,
			exp = 297801,
			levelExp = 25560,
		},
		[44] = { 

			id = 44,
			exp = 324731,
			levelExp = 26930,
		},
		[45] = { 

			id = 45,
			exp = 353031,
			levelExp = 28300,
		},
		[46] = { 

			id = 46,
			exp = 382701,
			levelExp = 29670,
		},
		[47] = { 

			id = 47,
			exp = 413741,
			levelExp = 31040,
		},
		[48] = { 

			id = 48,
			exp = 446151,
			levelExp = 32410,
		},
		[49] = { 

			id = 49,
			exp = 479931,
			levelExp = 33780,
		},
		[50] = { 

			id = 50,
			exp = 515081,
			levelExp = 35150,
		},
		[51] = { 

			id = 51,
			exp = 552566,
			levelExp = 37485,
		},
		[52] = { 

			id = 52,
			exp = 592386,
			levelExp = 39820,
		},
		[53] = { 

			id = 53,
			exp = 634541,
			levelExp = 42155,
		},
		[54] = { 

			id = 54,
			exp = 679031,
			levelExp = 44490,
		},
		[55] = { 

			id = 55,
			exp = 725856,
			levelExp = 46825,
		},
		[56] = { 

			id = 56,
			exp = 775016,
			levelExp = 49160,
		},
		[57] = { 

			id = 57,
			exp = 826511,
			levelExp = 51495,
		},
		[58] = { 

			id = 58,
			exp = 880341,
			levelExp = 53830,
		},
		[59] = { 

			id = 59,
			exp = 936506,
			levelExp = 56165,
		},
		[60] = { 

			id = 60,
			exp = 995006,
			levelExp = 58500,
		},
		[61] = { 

			id = 61,
			exp = 1057506,
			levelExp = 62500,
		},
		[62] = { 

			id = 62,
			exp = 1124006,
			levelExp = 66500,
		},
		[63] = { 

			id = 63,
			exp = 1194506,
			levelExp = 70500,
		},
		[64] = { 

			id = 64,
			exp = 1269006,
			levelExp = 74500,
		},
		[65] = { 

			id = 65,
			exp = 1347506,
			levelExp = 78500,
		},
		[66] = { 

			id = 66,
			exp = 1430006,
			levelExp = 82500,
		},
		[67] = { 

			id = 67,
			exp = 1516506,
			levelExp = 86500,
		},
		[68] = { 

			id = 68,
			exp = 1607006,
			levelExp = 90500,
		},
		[69] = { 

			id = 69,
			exp = 1701506,
			levelExp = 94500,
		},
		[70] = { 

			id = 70,
			exp = 1800006,
			levelExp = 98500,
		},
		[71] = { 

			id = 71,
			exp = 1904656,
			levelExp = 104650,
		},
		[72] = { 

			id = 72,
			exp = 2015456,
			levelExp = 110800,
		},
		[73] = { 

			id = 73,
			exp = 2132406,
			levelExp = 116950,
		},
		[74] = { 

			id = 74,
			exp = 2255506,
			levelExp = 123100,
		},
		[75] = { 

			id = 75,
			exp = 2384756,
			levelExp = 129250,
		},
		[76] = { 

			id = 76,
			exp = 2520156,
			levelExp = 135400,
		},
		[77] = { 

			id = 77,
			exp = 2661706,
			levelExp = 141550,
		},
		[78] = { 

			id = 78,
			exp = 2809406,
			levelExp = 147700,
		},
		[79] = { 

			id = 79,
			exp = 2963256,
			levelExp = 153850,
		},
		[80] = { 

			id = 80,
			exp = 3123256,
			levelExp = 160000,
		},
}
Count=80
