--This file is generated by tools!
--Please do not modify this file!
module("tableData_tDailyReward",package.seeall)
data = {


		[1] = { 

			id = 1,
			NeedTimes = 1,
			DailyReward = "1:21:100;1:19:100",
		},
		[2] = { 

			id = 2,
			NeedTimes = 5,
			DailyReward = "1:530002:1;1:21:300;1:19:300",
		},
		[3] = { 

			id = 3,
			NeedTimes = 10,
			DailyReward = "1:560005:1;1:21:600;1:19:600",
		},
}
Count=3
