--This file is generated by tools!
--Please do not modify this file!
--Dabian 2014-07-28.
DataDefine = {

	Soldier_StrengthAttribute_ID = 0,
	Soldier_StrengthAttribute_SoliderId = 1,
	Soldier_StrengthAttribute_Attribute = 2,
	Soldier_StrengthAttribute_AttributeValue = 3,

}