MenuList = 
{
    ActivityAll                     = "ActivityStage/ActivityAll",
    ActivityAll_empty               = "ActivityStage/ActivityAll_empty",
    ActivityArmy                    = "ActivityStage/ActivityArmy",
    ActivityBanner                  = "ActivityStage/ActivityBanner",
    ActivityBulletin                = "ActivityStage/ActivityBulletin",
    ActivityEntrance                = "ActivityStage/ActivityEntrance",
    ActivityForecast                = "ActivityStage/ActivityForecast",
    ActivityGrow                    = "ActivityStage/ActivityGrow",
    ActivityNotice                  = "ActivityStage/ActivityNotice",
    ActivityPveMonsterInfo          = "ActivityStage/ActivityPveMonsterInfo",
    ActivityRace                    = "ActivityStage/ActivityRace",
    ActivityStage                   = "ActivityStage/ActivityStage",
    ActivityTreasure                = "ActivityStage/ActivityTreasure",
    ArmRaceHisInfo                  = "ActivityStage/ArmRaceHisInfo",
    ArmRaceHisInfo_union            = "ActivityStage/ArmRaceHisInfo_union",
    ArmRaceInfo                     = "ActivityStage/ArmRaceInfo",
    ChapComplete                    = "ActivityStage/ChapComplete",
    DailyActivity                   = "ActivityStage/DailyActivity",
    DailyActivity_Share             = "ActivityStage/DailyActivity_Share",
    DailyActivity_Template1         = "ActivityStage/DailyActivity_Template1",
    DailyActivityHelp               = "ActivityStage/DailyActivityHelp",
    GrowGold                        = "ActivityStage/GrowGold",
    GrowRewards                     = "ActivityStage/GrowRewards",
    IntegrationSource               = "ActivityStage/IntegrationSource",
    KingsRoad                       = "ActivityStage/KingsRoad",
    MilitaryAction                  = "ActivityStage/MilitaryAction",
    RebelArmyAttack                 = "ActivityStage/RebelArmyAttack",
    RebelArmyAttackHelp             = "ActivityStage/RebelArmyAttackHelp",
    RebelArmyAttackrank             = "ActivityStage/RebelArmyAttackrank",
    RebelArmyAttackRewards          = "ActivityStage/RebelArmyAttackRewards",
    RebelGoldInstru                 = "ActivityStage/RebelGoldInstru",
    SevenDay                        = "ActivityStage/SevenDay",
    SupplyCollect                   = "ActivityStage/SupplyCollect",
    SupplyCollectRewards            = "ActivityStage/SupplyCollectRewards",
    HolidayActivity                 = "ActivityStage/HolidayActivity",
    SupplyCollectRanking            = "ActivityStage/SupplyCollectRanking",
    ThirtyDay                       = "ActivityStage/ThirtyDay",
    WelfareAll                      = "ActivityStage/WelfareAll",
    CD_Key                          = "ActivityStage/CD_Key",
    LevelRace                       = "ActivityStage/LevelRace",

    SelectArmy                      = "Army/SelectArmy",

    ItemListShow                    = "Bag/ItemListShow",
    ItemListShowNew                 = "Bag/ItemListShowNew",
    Shop                            = "Bag/Shop",
    SlgBag                          = "Bag/SlgBag",
    UseSelectBox                    = "Bag/UseSelectBox",
    BoxDetails                      = "Bag/BoxDetails",
    TemporaryBag                    = "Bag/TemporaryBag",
    UseItem                         = "Bag/UseItem",

    Barrack                         = "Barrack/Barrack",
    Barrack_Soldier                 = "Barrack/Barrack_soldier",
    Dissolution                     = "Barrack/Dissolution",

    BuildingDetails                 = "BuildingCommon/BuildingDetails",
    BuildingLocked                  = "BuildingCommon/BuildingLocked",
    BuildingUpgrade                 = "BuildingCommon/BuildingUpgrade",
    CommonItemBag                   = "BuildingCommon/CommonItemBag",
    CommonItemBagHelp               = "BuildingCommon/CommonItemBagHelp",
    PowerUp                         = "BuildingCommon/PowerUp",
    QuickUseItem                    = "BuildingCommon/QuickUseItem",
    ResBar                          = "BuildingCommon/ResBar",
    Speedup                         = "BuildingCommon/Speedup",

    ChapterInfoUI                   = "ChapterInfo/ChapterInfoUI",
    ChapterPVPInfo                  = "ChapterInfo/ChapterPVPInfo",
    Sweep                           = "ChapterInfo/Sweep",

    ChapterSelectUI                 = "ChapterSelect/ChapterSelectUI",
    SectionRewards                  = "ChapterSelect/SectionRewards",
    SandSelect                      = "ChapterSelect/SandSelect",

    Chat                            = "Chat/Chat",
    UnionMessage                    = "Chat/UnionMessage",
	GroupSetting					= "Chat/group_setting",
	GroupSelectList					= "Chat/groups_selectlist",
	PanelBox						= "Chat/Panel_box",

    BuildingLevelup                 = "CommandCenter/BuildingLevelup",
    CommandCenter                   = "CommandCenter/CommandCenter",
    SoldierUnlock                   = "CommandCenter/SoldierUnlock",

    Embassy                         = "Embassy/Embassy",
    ExistTest                       = "ExistTest/ExistTest",
    ExistTestHelp                   = "ExistTest/ExistTestHelp",
    ExistTestNotice                 = "ExistTest/ExistTestNotice",

    Equip                           = "equip/Equip",
    --EquipBuild                      = "equip/EquipBuild",
    --EquipCompound                   = "equip/EquipCompound",
    --EquipInfo                       = "equip/EquipInfo",
    --EquipMap                        = "equip/EquipMap",
    EquipSelect                     = "equip/EquipSelect",
	
	--装备改版
    EquipSelectNew                  = "equip/EquipSelectNew",
    EquipBuildNew                   = "equip/EquipBuildNew",
    EquipMainNew                   = "equip/EquipMainNew",

    FirstPurchase                   = "FirstPurchase/FirstPurchase",

    Fort_predict                    = "Fort/Fort_predict",
    FortHistory                     = "Fort/FortHistory",
    FortInfo                        = "Fort/FortInfo",
    FortInfoall                     = "Fort/FortInfoall",
    FortOccuRule                    = "Fort/FortOccuRule",
    FortRule                        = "Fort/FortRule",

    BatteryAttackinfo               = "Government/BatteryAttackinfo",
    BatteryTarget                   = "Government/BatteryTarget",
    BatteryTarget_add               = "Government/BatteryTarget_add",
    City_lord                       = "Government/City_lord",
    FortressInfoall                 = "Government/FortressInfoall",
    StrongholdInfoall               = "Government/FortressInfoall",
    FortressWarinfo                 = "Government/FortressWarinfo",
    GOV_Authority                   = "Government/GOV_Authority",
    GOV_Help                        = "Government/GOV_Help",
    GOV_Main                        = "Government/GOV_Main",
    GOV_Officialinfo                = "Government/GOV_Officialinfo",
    GOV_predict                     = "Government/GOV_predict",
    GOV_Tax                         = "Government/GOV_Tax",
    GOVBanner                       = "Government/GOVBanner",
    GOVWarinfo                      = "Government/GOVWarinfo",
    StrongholdWarinfo               = "Government/StrongholdWarinfo",
    Union_Officialinfo              = "Government/Union_Officialinfo",
    Runebag                         = "Rune/Runebag",
    Sellmultiplerunes               = "Rune/Sellmultiplerunes",
    Selectrunes                     = "Rune/Selectrunes",
    Sellitem                        = "Rune/Sellitem",
    Sellrune                        = "Rune/Sellrune",
    Runedraw                        = "Rune/Runedraw",
    Getnewrune                      = "Rune/Getnewrune",
    Buyrunes                        = "Rune/Buyrunes",
    Guide                           = "Guide/Guide",
    Story                           = "Guide/Story",
    

    BadgeInfo                       = "Hero/BadgeInfo",
    BadgeInfoNew_1                  = "Hero/BadgeInfoNew_1",
    BasicParameters                 = "Hero/BasicParameters",
    HeroInfo                        = "Hero/HeroInfo",
    HeroInfoNew                     = "Hero/HeroInfoNew",
    HeroLevelUp                     = "Hero/HeroLevelUp",
    HeroList                        = "Hero/HeroList",
    HeroListNew                     = "Hero/HeroListNew",
    HeroStarUp                      = "Hero/HeroStarUp",
    HeroStarUpNew                   = "Hero/HeroStarUpNew",
	HeroSkillUpNew                   = "Hero/HeroSkillUpNew",
    HeroUnlock                      = "Hero/HeroUnlock",
    HeroUpgrade                     = "Hero/HeroUpgrade",
    SelectHero                      = "Hero/SelectHero",
    SellHeroItem                    = "Hero/SellHeroItem",
    UniversalPiece                  = "Hero/UniversalPiece",
    HeroSkillLevelup                = "Hero/HeroSkillLevelup",
	HeroEquipBuildNew               = "equip/HeroEquipBuildNew",

    AppointSuccess                  = "HeroAppoint/AppointSuccess",
    HeroAppoint                     = "HeroAppoint/HeroAppoint",
    HeroAppointUI                   = "HeroAppoint/HeroAppointUI",

    InGameUI                        = "InGame/InGameUI",
    pause                           = "InGame/pause",
    WinLose                         = "InGame/WinLose",

    GatherItemUI                    = "Item/GatherItemUI",

    JailInfo                        = "Jail/JailInfo",
    JailTreat                       = "Jail/JailTreat",
    Prisonerhelp                    = "Jail/Prisonerhelp",

    Laboratory                      = "Laboratory/Laboratory",
    LaboratoryDetails               = "Laboratory/LaboratoryDetails",
    LaboratoryUpgrade               = "Laboratory/LaboratoryUpgrade",

    loading                         = "loading/loading",
    LoadingMap                      = "loading/loading_map",
    update                          = "loading/update",
    update_ui                       = "loading/update_ui",

    BeatText                        = "Login/BeatText",
    ChooseZone                      = "Login/ChooseZone",
    GM                              = "Login/GM",
    GMLog                           = "Login/GMLog",
    login                           = "Login/login",
    Notice                          = "Login/Notice",
    Update_Repair                   = "Login/Update_Repair",
    UpdateVersion                   = "Login/UpdateVersion",
    Waiting                         = "Login/Waiting",

    LuaConsole                      = "LuaConsole/LuaConsole",

    Mail                            = "Mail/Mail",
    Mail_share                      = "Mail/Mail_share",
    MailDoc                     	= "Mail/MailDoc",
    MailNew                     	= "Mail/MailNew",
    MailReportDocNew                = "Mail/MailPve",
    MailReportSpyonDoc              = "Mail/MailSpy",

    BuffView                        = "MainCity/BuffView",
    FirstChangeName                 = "MainCity/FirstChangeName",
    HotTime                         = "MainCity/HotTime",
    MainCityUI                      = "MainCity/MainCityUI",
    Notice_Tips                     = "MainCity/Notice_Tips",
    Offlinerepo                     = "MainCity/Offlinerepo",
    online                          = "MainCity/online",
    ShareCommon                     = "MainCity/ShareCommon",
    ShareUnion                      = "MainCity/ShareUnion",
    UnionGuide                      = "MainCity/UnionGuide",
    WebPlugnUI                      = "MainCity/WebPlugnUI",

    MessageBox                      = "MessageBox/MessageBox",

    MilitarySchool                  = "MilitarySchool/MilitarySchool",
    OneCardDisplay                  = "MilitarySchool/OneCardDisplay",
    Preview                         = "MilitarySchool/Preview",
    TenCardDisplay                  = "MilitarySchool/TenCardDisplay",

    MissionUI                       = "Mission/MissionUI",

    NumberInput                     = "NumberInput/NumberInput",

    ParadeGround                    = "ParadeGround/ParadeGround",

    BoxShow                         = "Pay/BoxShow",
    Goldstore                       = "Pay/Goldstore",
    Goldstore_template1             = "Pay/Goldstore_template1",
    Goldstore_template2             = "Pay/Goldstore_template2",
    Goldstore_template3             = "Pay/Goldstore_template3",
    HeroCard_reward                 = "Pay/HeroCard_reward",
    MonthCard_reward                = "Pay/MonthCard_reward",
    Pay                             = "Pay/Pay",
    store                           = "Pay/store",
    store_template2                 = "Pay/store_template2",
    TimedBag                        = "Pay/TimedBag",
    TimedBag_Gold                   = "Pay/TimedBag_Gold",
    TimedBag_common                 = "Pay/TimedBag_common",
    TimedBag_notime                 = "Pay/TimedBag_notime",

    ChangeName                      = "PlayerInformation/ChangeName",
    ChooseFlag                      = "PlayerInformation/ChooseFlag",
    --EquipChange                     = "PlayerInformation/EquipChange",
    MainInformation                 = "PlayerInformation/MainInformation",
    OtherInfo                       = "PlayerInformation/OtherInfo",
    PlayerLevelup                   = "PlayerInformation/PlayerLevelup",
    RansomPay                       = "PlayerInformation/RansomPay",
    WantedPrice                     = "PlayerInformation/WantedPrice",
	SoldierLevel					= "PlayerInformation/SoldierLevel",
	SoldierLevelSure				= "PlayerInformation/SoldierLevel_sure",
	Statistic                       = "PlayerInformation/Statistic",
	MilitaryRank                    = "PlayerInformation/MilitaryRank",

    BattlefieldReport               = "PVP/BattlefieldReport",
    PVP_Rewards                     = "PVP/PVP_Rewards",
    PVP_SLG                         = "PVP/PVP_SLG",
    PVPUI                           = "PVP/PVPUI",
    UnitCounters                    = "PVP/UnitCounters",

    Marchlist                       = "radar/Marchlist",

    instructions                    = "rebel/instructions",
    rebel                           = "rebel/rebel",
    rebel_history                   = "rebel/rebel_history",
    rebel_predict                   = "rebel/rebel_predict",
    rebel_reward                    = "rebel/rebel_reward",

    RebelArmyWanted                 = "RebelArmyWanted/RebelArmyWanted",

    RebelArmy                       = "RebelBase/RebelArmy",
    UnionRadar                      = "RebelBase/UnionRadar",
    UnionRadarHis                   = "RebelBase/UnionRadarHis",

    RebelSurround                   = "RebelSurround/RebelSurround",
    RebelSurround_ins               = "RebelSurround/RebelSurround_ins",
    RebelSurround_report            = "RebelSurround/RebelSurround_report",
    RebelSurround_spy               = "RebelSurround/RebelSurround_spy",
    RebelSurround_TileInfo          = "RebelSurround/RebelSurround_TileInfo",
    RebelSurrounddefenceshow        = "RebelSurround/RebelSurrounddefenceshow",
    RebelSurroundNew                = "RebelSurround/RebelSurroundNew",
    RebelSurroundNew_advance        = "RebelSurround/RebelSurroundNew_advance",
    RebelSurroundrewardList         = "RebelSurround/RebelSurroundrewardList",

    Hospital                        = "Resource/Hospital",
    ResView                         = "Resource/ResView",
    ResViewDetails                  = "Resource/ResViewDetails",

    BuildReview                     = "review/BuildReview",
    OtherView                       = "review/OtherView",

    account                         = "setting/account",
    feedback                        = "setting/feedback",
    options                         = "setting/options",
    rank                            = "setting/rank",
    setting                         = "setting/setting",
    SettingNotice                   = "setting/SettingNotice",
	SettingBlackList                   = "setting/SettingBlackList",


    TalentDetail                    = "TalentPoint/TalentDetail",
    TalentInfo                      = "TalentPoint/TalentInfo",
    TalentUpgrade                   = "TalentPoint/TalentUpgrade",

    TileInfo                        = "TileInfo/TileInfo",

    Trade                           = "TradeHall/Trade",
    TradeHall                       = "TradeHall/TradeHall",

    ChapterPicture                  = "Tutorial/ChapterPicture",
    GrowFemale                      = "Tutorial/GrowFemale",
    GrowGuide                       = "Tutorial/GrowGuide",
    MapHelp                         = "Tutorial/MapHelp",
    MapMask                         = "Tutorial/MapMask",
    Starwars                        = "Tutorial/Starwars",
    StoryPicture                    = "Tutorial/StoryPicture",
    Tutorial                        = "Tutorial/Tutorial",
    Strategy                        = "Tutorial/Strategy",

    JoinUnion                       = "Union/JoinUnion",
    UnionApprove                    = "Union/UnionApprove",
    UnionAuthority                  = "Union/UnionAuthority",
    UnionBadge                      = "Union/UnionBadge",
    UnionDomain                     = "Union/UnionDomain",
    UnionFunction                   = "Union/UnionFunction",
    UnionGift                       = "Union/UnionGift",
    UnionHelp                       = "Union/UnionHelp",
    UnionInfo                       = "Union/UnionInfo",
    UnionBuff                       = "Union/UnionBuff",
    UnionWar                        = "Union/UnionWar",
    UnionBuilding                   = "Union/UnionBuilding",
    UnionCity                       = "Union/UnionCity",
    UnionName                       = "Union/UnionName",
    UnionCode                       = "Union/UnionCode",
    UnionLanguage                   = "Union/UnionLanguage",
    UnionList                       = "Union/UnionList",
    UnionLog                        = "Union/UnionLog",
    UnionManagement                 = "Union/UnionManagement",
    UnionMemberLevel                = "Union/UnionMemberLevel",
    UnionMemberRank                 = "Union/UnionMemberRank",
    UnionPubinfo                    = "Union/UnionPubinfo",
    UnionRank                       = "Union/UnionRank",
    UnionSetLevel                   = "Union/UnionSetLevel",
    UnionShop                       = "Union/UnionShop",
    UnionSuperOre                   = "Union/UnionSuperOre",
    UnionTec                        = "Union/UnionTec",
    UnionTrain                      = "Union/UnionTrain",
    UnionWareHouse                  = "Union/UnionWareHouse",
    UnionWareHouseHis               = "Union/UnionWareHouseHis",
    Union_donate                    = "Union/Union_donate",
    UnionEdit                       = "Union/UnionEdit",
    SectionRewards_union            = "Union/SectionRewards_union",

    GetVipCoin                      = "Vip/GetVIPCion",
    VIP                             = "Vip/VIP",
    VIPLevelup                      = "Vip/VIPLevelup",
    TimedBag_VIP                    = "Vip/TimedBag_VIP",
    VipExp                          = "VIP/VIPLoginReward",

    WallHero                        = "wall/WallHero",
    WallInfo                        = "wall/WallInfo",

    WareHouse                       = "WareHouse/WareHouse",

    ResMap                          = "WarZoneMap/ResMap",
    TerritoryFilter                 = "WarZoneMap/TerritoryFilter",
    WarZoneMap                      = "WarZoneMap/WarZoneMap",

    ActionList                      = "WorldMap/ActionList",
    assembled_time                  = "WorldMap/assembled_time",
    BattleMove                      = "WorldMap/BattleMove",
    CoordInput                      = "WorldMap/CoordInput",
    EliteRebel                      = "WorldMap/EliteRebel",
    EliteRebelHelp                  = "WorldMap/EliteRebelHelp",
    Embattle                        = "WorldMap/Embattle",
    MapSearch                       = "WorldMap/MapSearch",
    PathInfo                        = "WorldMap/PathInfo",
    SelectHero_PVP                  = "WorldMap/SelectHero_PVP",
    StrongholdRule                  = "WorldMap/StrongholdRule",
    Traget_Set                      = "WorldMap/Traget_Set",
    Traget_Share                    = "WorldMap/Traget_Share",
    Traget_View                     = "WorldMap/Traget_View",
    WarZoneUI                       = "WorldMap/WarZoneUI",
    WorldMap                        = "WorldMap/WorldMap",
    WorldMapZoneUI                  = "WorldMap/WorldMapZoneUI",
    PVP_ATK_Activity                = "ActivityStage/PVP_ATK_Activity",
    PVP_ATK_DisRank                 = "ActivityStage/PVP_ATK_DisRank",
    PAP_ATK_Banner                  = "ActivityStage/PAP_ATK_Banner",
    Climb                           = "Climb/Climb",
    ClimbInfo                       = "Climb/ClimbInfo",
    ClimbReward                     = "Climb/ClimbReward",

    DailyActivity_Worldcup          = "ActivityStage/DailyActivity_Worldcup",
    DailyActivity_WorldcupGuss      = "ActivityStage/DailyActivity_WorldcupGuss",

    DailyActivity_ContinueRecharge  = "ActivityStage/DailyActivity_ContinueRecharge",
    Welfare_heroget                 = "ActivityStage/Welfare_heroget",
    RechargeRewards                 = "ChapterSelect/SectionRewards",
    LuckyRotary                     = "LuckyRotary/LuckyRotary",
	Christmas                     	= "ActivityStage/Christmas",
	ChristmasRewards				= "ActivityStage/Christmas_RersonReward",
	ChristmasRank					= "ActivityStage/Christmas_rank",
	ChristmasHelp					= "ActivityStage/Christmas_Help",
	
    LuckyRotaryReward               = "ChapterSelect/SectionRewards",
	CompensateList 					= "radar/Marchlist",
    PVP_LuckyRotary                 = "ActivityStage/PVP_LuckyRotary",
	PVP_LuckyRotary_Select          = "ActivityStage/PVP_LuckyRotary_Select",
	PVP_LuckyRotary_Sure            = "ActivityStage/PVP_LuckyRotary_Sure",
    PVP_LuckyRotary_Help            = "ActivityStage/PVP_LuckyRotary_Help",
    PVP_LuckyRotaryReward           = "ChapterSelect/SectionRewards",
    TenHero                         = "ActivityStage/TenHero",
    Barrack_SoldierEquip            = "Barrack/Barrack_SoldierEquip",
    SoliderUpgrade                  = "TileInfo/SoliderUpgrade",
    SoldierEquipBanner              = "Barrack/SoldierEquipBanner",
    DefenceNumber                   = "MainCity/DefenceNumber",
	
    Rune							= "Rune/Rune",
    rategame                        = "MainCity/rategame",

    NewRace                         = "NewRace/NewRace",
    NewRaceRredict                  = "NewRace/NewRaceRredict",
    NewRaceResult                   = "NewRace/NewRaceResult",
    NewRaceBanner                   = "NewRace/NewRaceBanner",
    NewRaceReward                   = "ChapterSelect/SectionRewards",
    NewRaceSource                   = "NewRace/NewRaceSource",
    NewRaceRank                     = "NewRace/NewRaceRank",
    NewRaceHelp                     = "NewRace/NewRaceHelp",
    NewActivityBanner               = "NewRace/NewActivityBanner",
    SoldierProduction               = "MainCity/SoldierProduction",
	MobaMain               			= "Moba/MobaMain",
    MobaTileInfo                    = "TileInfo/TileInfo",
    MobaBattleMove                  = "Moba/MobaBattleMove",
    MobaSelectHero_PVP              = "WorldMap/SelectHero_PVP",
    MobaWallHero                    = "Moba/MobaWallHero",
    MobaUnionWar                    = "Moba/MobaUnionWar",
    MobaEmbassy                     = "Moba/MobaEmbassy",
	MobaActionList                  = "WorldMap/ActionList",
    Entrance                        = "Moba/Entrance",
    MobaRankreward                  = "Moba/MobaRankreward",
	MobaEmbattle					= "WorldMap/Embattle",	
    MobaParadeGround                = "Moba/MobaParadeGround",
	MobaWarZoneMap					= "Moba/MobaWarZoneMap",
	MobaStoreBuy                    = "Moba/MobaStore_buy",
    MobaStore                  		= "Moba/MobaStore",
	MobaPoint                    	= "Moba/Mobapoint",
    Moba_winlose                    = "Moba/Moba_winlose",
    Mobaconclusion                  = "Moba/Mobaconclusion",
	MobaChat						= "Chat/Chat",
	GuildMobaChat						= "Chat/Chat",
    MobaRank                        = "setting/rank",
    Mobaroleselect                  = "Moba/Mobaroleselect",
	MobaPersonalInfo                = "Moba/MobaPersonalInfo",
    MobaTraget_Share				= "WorldMap/Traget_Share",
    mobafile                        = "Moba/mobafile",
    Mobahistory                     = "Moba/Mobahistory",
    MobaMarchlist                   = "radar/Marchlist",

	AllianceMatch                   = "Moba/AllianceMatch",
	AllianceRank                    = "Moba/AllianceRank",
    GuildWarMain               		= "Moba/GuildWarMain",
    AllianceLogin                   = "Moba/AllianceLogin",
    AllianceUnionSelect             = "Moba/AllianceUnionSelect",
    BattleTime                      = "Moba/BattleTime",
    AllianceHistory                 = "Moba/AllianceHistory",
	
	BattleHistory                  	= "Arena/BattleHistory",
	
    Skin                            = "Skin/Skin",
    Skin_check                      = "Skin/Skin_check",
    Skin_other                      = "Skin/Skin_other",
	MobaBuffView					= "Moba/MobaBuffView",
    MobaResBar					    = "Moba/MobaResBar",
    
    QueueLease					    = "VIP/QueueLease",
    
    GetStrong                       = "ActivityStage/Getstrong",
	BattleRank                      = "Arena/BattleRank",
	BattleFormation                 = "Arena/BattleFormation",
	RankList                        = "Arena/RankList",
	SelectHero_Arena                = "WorldMap/SelectHero_PVP",
    ArenaRewards                    = "ChapterSelect/SectionRewards",
    Arena_Help                      = "Arena/Arena_Help",
    Npcinfo                         = "Arena/Npcinfo",
	CityList                        = "CityBattle/CityList",
    CityMap                         = "CityBattle/CityMap",

    PVP_Rewards_Skip                = "PVP/PVP_Rewards_Skip",
    Reinforcement                   = "Moba/Reinforcement",
    PowerRank                       = "ActivityStage/PowerRank",
    ZeroYuanGift                       = "Pay/0YuanGift",
    HeroEquipSelectNew                       = "Equip/HeroEquipSelectNew",
    Rebate_LuckyRotary              = "ActivityStage/Rebate_LuckyRotary",
    ReturnRewards                   = "ActivityStage/ReturnRewards",
}
