//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameSetting_ESavingTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(GameSetting.ESavingType));
		L.RegVar("ePlayerData", get_ePlayerData, null);
		L.RegVar("eOptions", get_eOptions, null);
		L.RegVar("eBattle", get_eBattle, null);
		L.RegVar("eGuide", get_eGuide, null);
		L.RegVar("eCount", get_eCount, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ePlayerData(IntPtr L)
	{
		ToLua.Push(L, GameSetting.ESavingType.ePlayerData);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eOptions(IntPtr L)
	{
		ToLua.Push(L, GameSetting.ESavingType.eOptions);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eBattle(IntPtr L)
	{
		ToLua.Push(L, GameSetting.ESavingType.eBattle);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eGuide(IntPtr L)
	{
		ToLua.Push(L, GameSetting.ESavingType.eGuide);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eCount(IntPtr L)
	{
		ToLua.Push(L, GameSetting.ESavingType.eCount);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		GameSetting.ESavingType o = (GameSetting.ESavingType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

