//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameEnviromentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameEnviroment), typeof(System.Object));
		L.RegFunction("New", _CreateGameEnviroment);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("NETWORK_ENV", get_NETWORK_ENV, set_NETWORK_ENV);
		L.RegVar("NeedAndroidObb", get_NeedAndroidObb, set_NeedAndroidObb);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameEnviroment(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameEnviroment obj = new GameEnviroment();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameEnviroment.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NETWORK_ENV(IntPtr L)
	{
		try
		{
			ToLua.Push(L, GameEnviroment.NETWORK_ENV);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NeedAndroidObb(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, GameEnviroment.NeedAndroidObb);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_NETWORK_ENV(IntPtr L)
	{
		try
		{
			GameEnviroment.EEnviroment arg0 = (GameEnviroment.EEnviroment)ToLua.CheckObject(L, 2, typeof(GameEnviroment.EEnviroment));
			GameEnviroment.NETWORK_ENV = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_NeedAndroidObb(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			GameEnviroment.NeedAndroidObb = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

