//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ProtoMsg_SEntryGuildBuildWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ProtoMsg.SEntryGuildBuild), typeof(System.Object));
		L.RegFunction("New", _CreateProtoMsg_SEntryGuildBuild);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("baseid", get_baseid, set_baseid);
		L.RegVar("completetime", get_completetime, set_completetime);
		L.RegVar("isCompleted", get_isCompleted, set_isCompleted);
		L.RegVar("lifeTime", get_lifeTime, set_lifeTime);
		L.RegVar("hasSelfArmy", get_hasSelfArmy, set_hasSelfArmy);
		L.RegVar("totalSpeed", get_totalSpeed, set_totalSpeed);
		L.RegVar("selfSpeed", get_selfSpeed, set_selfSpeed);
		L.RegVar("totalRemaining", get_totalRemaining, set_totalRemaining);
		L.RegVar("selfGather", get_selfGather, set_selfGather);
		L.RegVar("removeTime", get_removeTime, set_removeTime);
		L.RegVar("selfTakeTime", get_selfTakeTime, set_selfTakeTime);
		L.RegVar("curCreatePro", get_curCreatePro, set_curCreatePro);
		L.RegVar("countdown", get_countdown, set_countdown);
		L.RegVar("nowTime", get_nowTime, set_nowTime);
		L.RegVar("extraSpeed", get_extraSpeed, set_extraSpeed);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateProtoMsg_SEntryGuildBuild(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ProtoMsg.SEntryGuildBuild obj = new ProtoMsg.SEntryGuildBuild();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ProtoMsg.SEntryGuildBuild.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_baseid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.baseid;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index baseid on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_completetime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.completetime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index completetime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isCompleted(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			bool ret = obj.isCompleted;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isCompleted on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_lifeTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.lifeTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index lifeTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hasSelfArmy(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			bool ret = obj.hasSelfArmy;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index hasSelfArmy on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_totalSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.totalSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index totalSpeed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_selfSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.selfSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index selfSpeed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_totalRemaining(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.totalRemaining;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index totalRemaining on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_selfGather(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.selfGather;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index selfGather on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_removeTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.removeTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index removeTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_selfTakeTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.selfTakeTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index selfTakeTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_curCreatePro(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.curCreatePro;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index curCreatePro on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_countdown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			bool ret = obj.countdown;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index countdown on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_nowTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint ret = obj.nowTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index nowTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_extraSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			float ret = obj.extraSpeed;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index extraSpeed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_baseid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.baseid = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index baseid on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_completetime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.completetime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index completetime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_isCompleted(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.isCompleted = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isCompleted on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_lifeTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.lifeTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index lifeTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_hasSelfArmy(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.hasSelfArmy = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index hasSelfArmy on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_totalSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.totalSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index totalSpeed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_selfSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.selfSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index selfSpeed on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_totalRemaining(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.totalRemaining = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index totalRemaining on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_selfGather(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.selfGather = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index selfGather on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_removeTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.removeTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index removeTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_selfTakeTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.selfTakeTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index selfTakeTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_curCreatePro(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.curCreatePro = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index curCreatePro on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_countdown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.countdown = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index countdown on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_nowTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.nowTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index nowTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_extraSpeed(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryGuildBuild obj = (ProtoMsg.SEntryGuildBuild)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.extraSpeed = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index extraSpeed on a nil value" : e.Message);
		}
	}
}

