//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ProtoMsg_SEntryHomeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ProtoMsg.SEntryHome), typeof(System.Object));
		L.RegFunction("New", _CreateProtoMsg_SEntryHome);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("charid", get_charid, set_charid);
		L.RegVar("name", get_name, set_name);
		L.RegVar("homelvl", get_homelvl, set_homelvl);
		L.RegVar("pkvalue", get_pkvalue, set_pkvalue);
		L.RegVar("guildId", get_guildId, set_guildId);
		L.RegVar("hasShield", get_hasShield, set_hasShield);
		L.RegVar("status", get_status, set_status);
		L.RegVar("statusTime", get_statusTime, set_statusTime);
		L.RegVar("fortBadge", get_fortBadge, set_fortBadge);
		L.RegVar("hasFortArroundBuff", get_hasFortArroundBuff, set_hasFortArroundBuff);
		L.RegVar("officialId", get_officialId, set_officialId);
		L.RegVar("privilege", get_privilege, set_privilege);
		L.RegVar("nemesisArround", get_nemesisArround, set_nemesisArround);
		L.RegVar("nationality", get_nationality, set_nationality);
		L.RegVar("guildOfficialId", get_guildOfficialId, set_guildOfficialId);
		L.RegVar("strongholdAround", get_strongholdAround, set_strongholdAround);
		L.RegVar("prisoner", get_prisoner, set_prisoner);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateProtoMsg_SEntryHome(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ProtoMsg.SEntryHome obj = new ProtoMsg.SEntryHome();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ProtoMsg.SEntryHome.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_charid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.charid;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index charid on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			string ret = obj.name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index name on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_homelvl(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.homelvl;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index homelvl on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_pkvalue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			ulong ret = obj.pkvalue;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index pkvalue on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_guildId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.guildId;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index guildId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hasShield(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			bool ret = obj.hasShield;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index hasShield on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_status(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.status;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index status on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_statusTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.statusTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index statusTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_fortBadge(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.fortBadge;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index fortBadge on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hasFortArroundBuff(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			bool ret = obj.hasFortArroundBuff;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index hasFortArroundBuff on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_officialId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.officialId;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index officialId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_privilege(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.privilege;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index privilege on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_nemesisArround(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			bool ret = obj.nemesisArround;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index nemesisArround on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_nationality(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.nationality;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index nationality on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_guildOfficialId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint ret = obj.guildOfficialId;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index guildOfficialId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_strongholdAround(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			bool ret = obj.strongholdAround;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index strongholdAround on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_prisoner(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			ProtoMsg.SEntryPrisoner ret = obj.prisoner;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index prisoner on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_charid(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.charid = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index charid on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.name = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index name on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_homelvl(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.homelvl = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index homelvl on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_pkvalue(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			ulong arg0 = (ulong)LuaDLL.luaL_checknumber(L, 2);
			obj.pkvalue = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index pkvalue on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_guildId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.guildId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index guildId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_hasShield(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.hasShield = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index hasShield on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_status(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.status = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index status on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_statusTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.statusTime = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index statusTime on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_fortBadge(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.fortBadge = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index fortBadge on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_hasFortArroundBuff(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.hasFortArroundBuff = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index hasFortArroundBuff on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_officialId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.officialId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index officialId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_privilege(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.privilege = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index privilege on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_nemesisArround(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.nemesisArround = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index nemesisArround on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_nationality(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.nationality = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index nationality on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_guildOfficialId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.guildOfficialId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index guildOfficialId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_strongholdAround(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.strongholdAround = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index strongholdAround on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_prisoner(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProtoMsg.SEntryHome obj = (ProtoMsg.SEntryHome)o;
			ProtoMsg.SEntryPrisoner arg0 = (ProtoMsg.SEntryPrisoner)ToLua.CheckObject(L, 2, typeof(ProtoMsg.SEntryPrisoner));
			obj.prisoner = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index prisoner on a nil value" : e.Message);
		}
	}
}

