//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Serclimax_Player_ScPlayerInfoMsg_SkillInfoWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Serclimax.Player.ScPlayerInfoMsg.SkillInfo), typeof(System.Object));
		L.RegFunction("New", _CreateSerclimax_Player_ScPlayerInfoMsg_SkillInfo);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("heroId", get_heroId, set_heroId);
		L.RegVar("heroStar", get_heroStar, set_heroStar);
		L.RegVar("totalCooldown", get_totalCooldown, set_totalCooldown);
		L.RegVar("cooldown", get_cooldown, set_cooldown);
		L.RegVar("skillDataId", get_skillDataId, set_skillDataId);
		L.RegVar("skillLevel", get_skillLevel, set_skillLevel);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSerclimax_Player_ScPlayerInfoMsg_SkillInfo(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = new Serclimax.Player.ScPlayerInfoMsg.SkillInfo();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Serclimax.Player.ScPlayerInfoMsg.SkillInfo.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_heroId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			int ret = obj.heroId;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index heroId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_heroStar(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			int ret = obj.heroStar;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index heroStar on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_totalCooldown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			float ret = obj.totalCooldown;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index totalCooldown on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cooldown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			float ret = obj.cooldown;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index cooldown on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_skillDataId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			int ret = obj.skillDataId;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index skillDataId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_skillLevel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			int ret = obj.skillLevel;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index skillLevel on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_heroId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.heroId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index heroId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_heroStar(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.heroStar = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index heroStar on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_totalCooldown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.totalCooldown = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index totalCooldown on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cooldown(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cooldown = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index cooldown on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_skillDataId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.skillDataId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index skillDataId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_skillLevel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Player.ScPlayerInfoMsg.SkillInfo obj = (Serclimax.Player.ScPlayerInfoMsg.SkillInfo)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.skillLevel = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index skillLevel on a nil value" : e.Message);
		}
	}
}

