//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Serclimax_Unit_ScSoldierAttributeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Serclimax.Unit.ScSoldierAttribute), typeof(Serclimax.Unit.ScUnitAttribute));
		L.RegFunction("AnimStateToIdle", AnimStateToIdle);
		L.RegFunction("ResetStandby", ResetStandby);
		L.RegFunction("SetShielder", SetShielder);
		L.RegFunction("ExitShield", ExitShield);
		L.RegFunction("UpdateShieldState", UpdateShieldState);
		L.RegFunction("StopMove", StopMove);
		L.RegFunction("SetAttackTarget", SetAttackTarget);
		L.RegFunction("HasReachEnd", HasReachEnd);
		L.RegFunction("Move2Point", Move2Point);
		L.RegFunction("Break", Break);
		L.RegFunction("RegisterQuadSpace", RegisterQuadSpace);
		L.RegFunction("UpdateQuadSpace", UpdateQuadSpace);
		L.RegFunction("GetBaseCollider", GetBaseCollider);
		L.RegFunction("UpdateHitinfoMsg", UpdateHitinfoMsg);
		L.RegFunction("Update", Update);
		L.RegFunction("UpdateUnitAttribute", UpdateUnitAttribute);
		L.RegFunction("ResetMsg", ResetMsg);
		L.RegFunction("CollectMsg", CollectMsg);
		L.RegFunction("GetAttType", GetAttType);
		L.RegFunction("GetAttackWeight", GetAttackWeight);
		L.RegFunction("UpdateUnit_EnemyTarget", UpdateUnit_EnemyTarget);
		L.RegFunction("New", _CreateSerclimax_Unit_ScSoldierAttribute);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("AdvancedAnimState", get_AdvancedAnimState, set_AdvancedAnimState);
		L.RegVar("AttackState", get_AttackState, set_AttackState);
		L.RegVar("StandbyDuration", get_StandbyDuration, null);
		L.RegVar("IsStandby", get_IsStandby, null);
		L.RegVar("isShieldState", get_isShieldState, null);
		L.RegVar("UnitData", get_UnitData, null);
		L.RegVar("UnitAttributeDefense", get_UnitAttributeDefense, null);
		L.RegVar("UnitAttributeWeaponCoef", get_UnitAttributeWeaponCoef, null);
		L.RegVar("UnitAttributeMaxHp", get_UnitAttributeMaxHp, null);
		L.RegVar("Mover", get_Mover, null);
		L.RegVar("TargetPath", get_TargetPath, set_TargetPath);
		L.RegVar("TargetPathPosition", get_TargetPathPosition, set_TargetPathPosition);
		L.RegVar("NormalState", get_NormalState, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSerclimax_Unit_ScSoldierAttribute(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				Serclimax.Unit.ScUnit arg0 = (Serclimax.Unit.ScUnit)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScUnit));
				Serclimax.Unit.UnitParam arg1 = (Serclimax.Unit.UnitParam)ToLua.CheckObject(L, 2, typeof(Serclimax.Unit.UnitParam));
				Serclimax.Unit.ScSoldierAttribute obj = new Serclimax.Unit.ScSoldierAttribute(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Serclimax.Unit.ScSoldierAttribute.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AnimStateToIdle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			Serclimax.Unit.ScUnitAnimState arg0 = (Serclimax.Unit.ScUnitAnimState)ToLua.CheckObject(L, 2, typeof(Serclimax.Unit.ScUnitAnimState));
			obj.AnimStateToIdle(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetStandby(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			obj.ResetStandby();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetShielder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			Serclimax.Unit.ScUnit arg0 = (Serclimax.Unit.ScUnit)ToLua.CheckObject(L, 2, typeof(Serclimax.Unit.ScUnit));
			Serclimax.Unit.ScSlotNode arg1 = (Serclimax.Unit.ScSlotNode)ToLua.CheckObject(L, 3, typeof(Serclimax.Unit.ScSlotNode));
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			obj.SetShielder(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ExitShield(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			obj.ExitShield();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateShieldState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.UpdateShieldState(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StopMove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			obj.StopMove();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAttackTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			Serclimax.Unit.ScUnit arg0 = (Serclimax.Unit.ScUnit)ToLua.CheckObject(L, 2, typeof(Serclimax.Unit.ScUnit));
			obj.SetAttackTarget(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasReachEnd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			bool o = obj.HasReachEnd();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Move2Point(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			Fixedpoint.fVector3 arg0 = (Fixedpoint.fVector3)ToLua.CheckObject(L, 2, typeof(Fixedpoint.fVector3));
			obj.Move2Point(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Break(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			obj.Break();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterQuadSpace(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			obj.RegisterQuadSpace();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateQuadSpace(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			obj.UpdateQuadSpace();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBaseCollider(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			Serclimax.QuadSpace.ScCollider o = obj.GetBaseCollider();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateHitinfoMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			Serclimax.Unit.ScUnit arg0 = (Serclimax.Unit.ScUnit)ToLua.CheckObject(L, 2, typeof(Serclimax.Unit.ScUnit));
			Serclimax.QuadSpace.ScHitInfo arg1 = (Serclimax.QuadSpace.ScHitInfo)ToLua.CheckObject(L, 3, typeof(Serclimax.QuadSpace.ScHitInfo));
			obj.UpdateHitinfoMsg(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			bool o = obj.Update(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateUnitAttribute(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			bool o = obj.UpdateUnitAttribute(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			obj.ResetMsg();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CollectMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			obj.CollectMsg();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAttType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			int o = obj.GetAttType();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAttackWeight(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			int o = obj.GetAttackWeight();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateUnit_EnemyTarget(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)ToLua.CheckObject(L, 1, typeof(Serclimax.Unit.ScSoldierAttribute));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.UpdateUnit_EnemyTarget(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AdvancedAnimState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			int ret = obj.AdvancedAnimState;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index AdvancedAnimState on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AttackState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			bool ret = obj.AttackState;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index AttackState on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StandbyDuration(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			Fixedpoint.fInt ret = obj.StandbyDuration;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index StandbyDuration on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsStandby(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			bool ret = obj.IsStandby;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index IsStandby on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_isShieldState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			bool ret = obj.isShieldState;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index isShieldState on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UnitData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			Serclimax.Unit.ScUnitData ret = obj.UnitData;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UnitData on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UnitAttributeDefense(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			float ret = obj.UnitAttributeDefense;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UnitAttributeDefense on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UnitAttributeWeaponCoef(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			float ret = obj.UnitAttributeWeaponCoef;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UnitAttributeWeaponCoef on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UnitAttributeMaxHp(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			float ret = obj.UnitAttributeMaxHp;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index UnitAttributeMaxHp on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Mover(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			Serclimax.Unit.ScUnitMove ret = obj.Mover;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index Mover on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TargetPath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			int ret = obj.TargetPath;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index TargetPath on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TargetPathPosition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			Fixedpoint.fVector3 ret = obj.TargetPathPosition;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index TargetPathPosition on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NormalState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			bool ret = obj.NormalState;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index NormalState on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AdvancedAnimState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.AdvancedAnimState = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index AdvancedAnimState on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AttackState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.AttackState = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index AttackState on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TargetPath(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.TargetPath = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index TargetPath on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TargetPathPosition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.Unit.ScSoldierAttribute obj = (Serclimax.Unit.ScSoldierAttribute)o;
			Fixedpoint.fVector3 arg0 = (Fixedpoint.fVector3)ToLua.CheckObject(L, 2, typeof(Fixedpoint.fVector3));
			obj.TargetPathPosition = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index TargetPathPosition on a nil value" : e.Message);
		}
	}
}

