//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Serclimax_ScTableMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Serclimax.ScTableMgr), typeof(System.Object));
		L.RegFunction("Init", Init);
		L.RegFunction("GetGlobalData", GetGlobalData);
		L.RegFunction("GetChapterData", GetChapterData);
		L.RegFunction("GetChapterTable", GetChapterTable);
		L.RegFunction("GetBattleData", GetBattleData);
		L.RegFunction("GetTeamSlotTable", GetTeamSlotTable);
		L.RegFunction("GetStarConditionData", GetStarConditionData);
		L.RegFunction("GetGroupData", GetGroupData);
		L.RegFunction("GetUnitData", GetUnitData);
		L.RegFunction("GetWeaponData", GetWeaponData);
		L.RegFunction("GetGodSkillData", GetGodSkillData);
		L.RegFunction("GetGodSkillDataByIdLevel", GetGodSkillDataByIdLevel);
		L.RegFunction("GetDropData", GetDropData);
		L.RegFunction("GetDropShowData", GetDropShowData);
		L.RegFunction("GetDropTable", GetDropTable);
		L.RegFunction("GetSLGSkillTable", GetSLGSkillTable);
		L.RegFunction("GetItemData", GetItemData);
		L.RegFunction("GetItemDataByType", GetItemDataByType);
		L.RegFunction("GetBuildingData", GetBuildingData);
		L.RegFunction("GetAllBuildingData", GetAllBuildingData);
		L.RegFunction("GetUnitDefenseData", GetUnitDefenseData);
		L.RegFunction("GetBuildUpdateData", GetBuildUpdateData);
		L.RegFunction("GetLandListData", GetLandListData);
		L.RegFunction("GetBuildCoreDataByLevel", GetBuildCoreDataByLevel);
		L.RegFunction("GetBuildCoreData", GetBuildCoreData);
		L.RegFunction("GetAllBuildCoreData", GetAllBuildCoreData);
		L.RegFunction("GetBuildReviewData", GetBuildReviewData);
		L.RegFunction("GetGuideInfoData", GetGuideInfoData);
		L.RegFunction("GetBuildResourceData", GetBuildResourceData);
		L.RegFunction("GetBuildingResourceInfo", GetBuildingResourceInfo);
		L.RegFunction("GetBuildingResourceData", GetBuildingResourceData);
		L.RegFunction("GetBuildingResourceYield", GetBuildingResourceYield);
		L.RegFunction("GetGmTable", GetGmTable);
		L.RegFunction("GetBarrackTable", GetBarrackTable);
		L.RegFunction("GetBuffShowList", GetBuffShowList);
		L.RegFunction("GetBarrackData", GetBarrackData);
		L.RegFunction("GetBarrackDataByUnitId", GetBarrackDataByUnitId);
		L.RegFunction("GetUnionLogData", GetUnionLogData);
		L.RegFunction("GetStaminaPriceData", GetStaminaPriceData);
		L.RegFunction("GetStaminaPriceDataCount", GetStaminaPriceDataCount);
		L.RegFunction("GetWareDataTable", GetWareDataTable);
		L.RegFunction("GetWareData", GetWareData);
		L.RegFunction("GetWallDataTable", GetWallDataTable);
		L.RegFunction("GetWallData", GetWallData);
		L.RegFunction("GetCallUpTable", GetCallUpTable);
		L.RegFunction("GetCallUpData", GetCallUpData);
		L.RegFunction("GetClinicTable", GetClinicTable);
		L.RegFunction("GetClinicData", GetClinicData);
		L.RegFunction("GetParadeGroundData", GetParadeGroundData);
		L.RegFunction("GetParadeGroundTable", GetParadeGroundTable);
		L.RegFunction("GetRadarData", GetRadarData);
		L.RegFunction("GetRadarTable", GetRadarTable);
		L.RegFunction("GetSpeedUppriceTable", GetSpeedUppriceTable);
		L.RegFunction("GetBarrackBuildDataTable", GetBarrackBuildDataTable);
		L.RegFunction("GetPlayerExpData", GetPlayerExpData);
		L.RegFunction("GetPlayerExp", GetPlayerExp);
		L.RegFunction("GetPlayerLvupExp", GetPlayerLvupExp);
		L.RegFunction("GetHeroData", GetHeroData);
		L.RegFunction("GetHeroTable", GetHeroTable);
		L.RegFunction("GetHeroExpData", GetHeroExpData);
		L.RegFunction("GetMaxHeroLevel", GetMaxHeroLevel);
		L.RegFunction("GetHeroLevelByExp", GetHeroLevelByExp);
		L.RegFunction("GetHeroStarUpData", GetHeroStarUpData);
		L.RegFunction("GetHeroStarUpDataByHeroIdStarGrade", GetHeroStarUpDataByHeroIdStarGrade);
		L.RegFunction("GetHeroGradeUpData", GetHeroGradeUpData);
		L.RegFunction("GetHeroGradeUpDataByHeroIdGrade", GetHeroGradeUpDataByHeroIdGrade);
		L.RegFunction("GetBadgeData", GetBadgeData);
		L.RegFunction("GetBadgeDataByIdQuality", GetBadgeDataByIdQuality);
		L.RegFunction("GetRulesData", GetRulesData);
		L.RegFunction("GetRulesDataByStarGrade", GetRulesDataByStarGrade);
		L.RegFunction("GetNeedTextData", GetNeedTextData);
		L.RegFunction("GetNeedTextDataByAddition", GetNeedTextDataByAddition);
		L.RegFunction("GetFightData", GetFightData);
		L.RegFunction("GetCoefRuleList", GetCoefRuleList);
		L.RegFunction("GetResourcePriceData", GetResourcePriceData);
		L.RegFunction("GetTechDetailTable", GetTechDetailTable);
		L.RegFunction("GetTechDetailDataByIdLevel", GetTechDetailDataByIdLevel);
		L.RegFunction("GetTechCategoryTable", GetTechCategoryTable);
		L.RegFunction("GetBuildLaboratoryTable", GetBuildLaboratoryTable);
		L.RegFunction("GetSlgBuffData", GetSlgBuffData);
		L.RegFunction("GetSlgBuffTable", GetSlgBuffTable);
		L.RegFunction("GetItemExchangeData", GetItemExchangeData);
		L.RegFunction("GetUnionMonsterData", GetUnionMonsterData);
		L.RegFunction("GetUnionMonsterTable", GetUnionMonsterTable);
		L.RegFunction("GetPveMonsterData", GetPveMonsterData);
		L.RegFunction("GetItemExchangeList", GetItemExchangeList);
		L.RegFunction("GetItemExchangeListData", GetItemExchangeListData);
		L.RegFunction("GetBonusFunction", GetBonusFunction);
		L.RegFunction("GetSettingTable", GetSettingTable);
		L.RegFunction("GetMissionData", GetMissionData);
		L.RegFunction("GetMilitarytActionData", GetMilitarytActionData);
		L.RegFunction("GetMissionTutorialList", GetMissionTutorialList);
		L.RegFunction("GetVipDataList", GetVipDataList);
		L.RegFunction("GetVipGiftDataList", GetVipGiftDataList);
		L.RegFunction("GetVipPrivilegeDataList", GetVipPrivilegeDataList);
		L.RegFunction("GetFunctionUnlockText", GetFunctionUnlockText);
		L.RegFunction("GetFunctionUnlockLevel", GetFunctionUnlockLevel);
		L.RegFunction("GetResourceRuleDataByTypeLevel", GetResourceRuleDataByTypeLevel);
		L.RegFunction("GetResourceRuleData", GetResourceRuleData);
		L.RegFunction("GetMonsterRuleData", GetMonsterRuleData);
		L.RegFunction("GetMonsterRuleList", GetMonsterRuleList);
		L.RegFunction("GetEliteMonsterRuleData", GetEliteMonsterRuleData);
		L.RegFunction("GetActiveConditionData", GetActiveConditionData);
		L.RegFunction("GetMailCfgData", GetMailCfgData);
		L.RegFunction("GetBasicSurfaceDataByType", GetBasicSurfaceDataByType);
		L.RegFunction("GetArtSettingData", GetArtSettingData);
		L.RegFunction("GetArtSettingList", GetArtSettingList);
		L.RegFunction("GetObjectShapeData", GetObjectShapeData);
		L.RegFunction("GetObjectShapeList", GetObjectShapeList);
		L.RegFunction("GetRandomName", GetRandomName);
		L.RegFunction("GetSpyPrice", GetSpyPrice);
		L.RegFunction("GetLoginData", GetLoginData);
		L.RegFunction("GetSoldierShowRule", GetSoldierShowRule);
		L.RegFunction("GetUnionBadgeColorData", GetUnionBadgeColorData);
		L.RegFunction("GetUnionBadgeColorList", GetUnionBadgeColorList);
		L.RegFunction("GetUnionBadgeBorderData", GetUnionBadgeBorderData);
		L.RegFunction("GetUnionBadgeBorderList", GetUnionBadgeBorderList);
		L.RegFunction("GetUnionItemData", GetUnionItemData);
		L.RegFunction("GetUnionBuildingData", GetUnionBuildingData);
		L.RegFunction("GetUnionBuildingList", GetUnionBuildingList);
		L.RegFunction("GetUnionMineByResourceType", GetUnionMineByResourceType);
		L.RegFunction("GetUnionBadgeTotemData", GetUnionBadgeTotemData);
		L.RegFunction("GetUnionBadgeTotemList", GetUnionBadgeTotemList);
		L.RegFunction("GetUnionNumByType", GetUnionNumByType);
		L.RegFunction("GetUnionLanguageList", GetUnionLanguageList);
		L.RegFunction("GetUnionLanguageData", GetUnionLanguageData);
		L.RegFunction("GetTradingPostData", GetTradingPostData);
		L.RegFunction("GetUnionGiftExpData", GetUnionGiftExpData);
		L.RegFunction("GetTradingPostTable", GetTradingPostTable);
		L.RegFunction("GetEmbassyTable", GetEmbassyTable);
		L.RegFunction("GetEmbassyData", GetEmbassyData);
		L.RegFunction("GetAssembledTable", GetAssembledTable);
		L.RegFunction("GetAssembledData", GetAssembledData);
		L.RegFunction("GetActMonsterData", GetActMonsterData);
		L.RegFunction("GetActMonsterRuleData", GetActMonsterRuleData);
		L.RegFunction("GetTalentTable", GetTalentTable);
		L.RegFunction("GetTalentDataByIdLevel", GetTalentDataByIdLevel);
		L.RegFunction("GetTalentCategoryTable", GetTalentCategoryTable);
		L.RegFunction("GetUnionTechDetailTable", GetUnionTechDetailTable);
		L.RegFunction("GetActiveStaticsRule", GetActiveStaticsRule);
		L.RegFunction("GetActiveStaticsRuleData", GetActiveStaticsRuleData);
		L.RegFunction("GetActiveStaticsList", GetActiveStaticsList);
		L.RegFunction("GetActivityStaticsListData", GetActivityStaticsListData);
		L.RegFunction("GetActivityStaticsRewardData", GetActivityStaticsRewardData);
		L.RegFunction("GetActivityStaticsRewardDataById", GetActivityStaticsRewardDataById);
		L.RegFunction("GetUnionTechDetailDataByIdLevel", GetUnionTechDetailDataByIdLevel);
		L.RegFunction("GetEquipTable", GetEquipTable);
		L.RegFunction("GetMaterialTable", GetMaterialTable);
		L.RegFunction("GetArmouryData", GetArmouryData);
		L.RegFunction("GetEquipTextDataByAddition", GetEquipTextDataByAddition);
		L.RegFunction("GetPVEMoraleBonusFactor", GetPVEMoraleBonusFactor);
		L.RegFunction("GetPVEPhysiqueBonusFactor", GetPVEPhysiqueBonusFactor);
		L.RegFunction("GetActivityNoticeList", GetActivityNoticeList);
		L.RegFunction("GetPassiveSkillData", GetPassiveSkillData);
		L.RegFunction("GetActivitySiegeMonsterReward", GetActivitySiegeMonsterReward);
		L.RegFunction("GetActivitySiegeMonsterRankRewardByType", GetActivitySiegeMonsterRankRewardByType);
		L.RegFunction("GetMapBuildingDataByID", GetMapBuildingDataByID);
		L.RegFunction("GetStrongholdRuleByID", GetStrongholdRuleByID);
		L.RegFunction("GetFortressRuleByID", GetFortressRuleByID);
		L.RegFunction("GetUnionOfficialByID", GetUnionOfficialByID);
		L.RegFunction("GetOfficialByID", GetOfficialByID);
		L.RegFunction("GetMilitaryRankData", GetMilitaryRankData);
		L.RegFunction("GetMobaBuildingRuleData", GetMobaBuildingRuleData);
		L.RegFunction("GetGuildWarBuildingRuleData", GetGuildWarBuildingRuleData);
		L.RegFunction("GetWorldCityData", GetWorldCityData);
		L.RegFunction("New", _CreateSerclimax_ScTableMgr);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("assetbundleLoader", get_assetbundleLoader, set_assetbundleLoader);
		L.RegVar("ProductionSet", get_ProductionSet, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSerclimax_ScTableMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Serclimax.ScTableMgr obj = new Serclimax.ScTableMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Serclimax.ScTableMgr.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(Serclimax.ScTableMgr)))
			{
				Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.ToObject(L, 1);
				obj.Init();
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Serclimax.ScTableMgr), typeof(Serclimax.AssetbundleLoader)))
			{
				Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.ToObject(L, 1);
				Serclimax.AssetbundleLoader arg0 = (Serclimax.AssetbundleLoader)ToLua.ToObject(L, 2);
				obj.Init(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Serclimax.ScTableMgr.Init");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGlobalData(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Serclimax.ScTableMgr), typeof(int)))
			{
				Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				Serclimax.ScGlobalData o = obj.GetGlobalData(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Serclimax.ScTableMgr), typeof(Serclimax.ScGlobalDataId)))
			{
				Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.ToObject(L, 1);
				Serclimax.ScGlobalDataId arg0 = (Serclimax.ScGlobalDataId)ToLua.ToObject(L, 2);
				Serclimax.ScGlobalData o = obj.GetGlobalData(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Serclimax.ScTableMgr.GetGlobalData");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChapterData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScChapterData o = obj.GetChapterData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetChapterTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScChapterData> o = obj.GetChapterTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBattleData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBattleData o = obj.GetBattleData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTeamSlotTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScTeamSlotData> o = obj.GetTeamSlotTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetStarConditionData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScStarConditionData o = obj.GetStarConditionData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGroupData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.Unit.ScUnitGroupData o = obj.GetGroupData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnitData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.Unit.ScUnitData o = obj.GetUnitData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWeaponData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.Skill.ScSkillWeaponData o = obj.GetWeaponData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGodSkillData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScGodSkillData o = obj.GetGodSkillData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGodSkillDataByIdLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScGodSkillData o = obj.GetGodSkillDataByIdLevel(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDropData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScDropData o = obj.GetDropData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDropShowData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScDropShowData[] o = obj.GetDropShowData(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDropTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScDropData> o = obj.GetDropTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSLGSkillTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.SLGPVP.ScSLGSkillData> o = obj.GetSLGSkillTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetItemData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScItemData o = obj.GetItemData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetItemDataByType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScItemData[] o = obj.GetItemDataByType(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildingData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBuildingData o = obj.GetBuildingData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAllBuildingData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScBuildingData[] o = obj.GetAllBuildingData();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnitDefenseData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.Unit.ScUnitDefenseData o = obj.GetUnitDefenseData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildUpdateData(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Serclimax.ScTableMgr), typeof(int)))
			{
				Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				Serclimax.ScBuildingUpdateData o = obj.GetBuildUpdateData(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 3 && TypeChecker.CheckTypes(L, 1, typeof(Serclimax.ScTableMgr), typeof(int), typeof(int)))
			{
				Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				int arg1 = (int)LuaDLL.lua_tonumber(L, 3);
				Serclimax.ScBuildingUpdateData o = obj.GetBuildUpdateData(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Serclimax.ScTableMgr.GetBuildUpdateData");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLandListData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScLandListData o = obj.GetLandListData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildCoreDataByLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBuildingCoreData o = obj.GetBuildCoreDataByLevel(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildCoreData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBuildingCoreData o = obj.GetBuildCoreData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAllBuildCoreData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScBuildingCoreData[] o = obj.GetAllBuildCoreData();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildReviewData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScBuildingReviewData[] o = obj.GetBuildReviewData();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGuideInfoData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.GuideInfoData o = obj.GetGuideInfoData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildResourceData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBuildingResourceData o = obj.GetBuildResourceData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildingResourceInfo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBuildingResourceData[] o = obj.GetBuildingResourceInfo(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildingResourceData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScBuildingResourceData o = obj.GetBuildingResourceData(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildingResourceYield(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			int o = obj.GetBuildingResourceYield(arg0, arg1);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGmTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScGmData> o = obj.GetGmTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBarrackTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScBarrackData> o = obj.GetBarrackTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuffShowList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScSlgBuffListData> o = obj.GetBuffShowList();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBarrackData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScBarrackData o = obj.GetBarrackData(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBarrackDataByUnitId(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBarrackData o = obj.GetBarrackDataByUnitId(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionLogData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionLogData o = obj.GetUnionLogData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetStaminaPriceData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScStaminaPriceData o = obj.GetStaminaPriceData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetStaminaPriceDataCount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int o = obj.GetStaminaPriceDataCount();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWareDataTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScWareData> o = obj.GetWareDataTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWareData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScWareData o = obj.GetWareData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWallDataTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScWallData> o = obj.GetWallDataTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWallData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScWallData o = obj.GetWallData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCallUpTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScCallUpData> o = obj.GetCallUpTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCallUpData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScCallUpData o = obj.GetCallUpData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetClinicTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScClinicData> o = obj.GetClinicTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetClinicData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScClinicData o = obj.GetClinicData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetParadeGroundData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScParadeGroundData o = obj.GetParadeGroundData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetParadeGroundTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScParadeGroundData> o = obj.GetParadeGroundTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRadarData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScRadarData o = obj.GetRadarData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRadarTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScRadarData> o = obj.GetRadarTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSpeedUppriceTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScSpeedUppriceData> o = obj.GetSpeedUppriceTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBarrackBuildDataTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScBarrackBuildData> o = obj.GetBarrackBuildDataTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPlayerExpData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScPlayerExpData o = obj.GetPlayerExpData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPlayerExp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScPlayerExpData o = obj.GetPlayerExp(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPlayerLvupExp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
			float o = obj.GetPlayerLvupExp(arg0, arg1, arg2, arg3);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHeroData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScHeroData o = obj.GetHeroData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHeroTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScHeroData> o = obj.GetHeroTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHeroExpData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScHeroExpData o = obj.GetHeroExpData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMaxHeroLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int o = obj.GetMaxHeroLevel();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHeroLevelByExp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			float o = obj.GetHeroLevelByExp(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHeroStarUpData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScHeroStarUpData o = obj.GetHeroStarUpData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHeroStarUpDataByHeroIdStarGrade(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			int arg2 = (int)LuaDLL.luaL_checknumber(L, 4);
			Serclimax.ScHeroStarUpData o = obj.GetHeroStarUpDataByHeroIdStarGrade(arg0, arg1, arg2);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHeroGradeUpData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScHeroGradeUpData o = obj.GetHeroGradeUpData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHeroGradeUpDataByHeroIdGrade(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScHeroGradeUpData o = obj.GetHeroGradeUpDataByHeroIdGrade(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBadgeData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBadgeData o = obj.GetBadgeData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBadgeDataByIdQuality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScBadgeData o = obj.GetBadgeDataByIdQuality(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRulesData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScRulesData o = obj.GetRulesData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRulesDataByStarGrade(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScRulesData o = obj.GetRulesDataByStarGrade(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNeedTextData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScNeedTextData o = obj.GetNeedTextData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetNeedTextDataByAddition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScNeedTextData o = obj.GetNeedTextDataByAddition(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFightData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScFightData o = obj.GetFightData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCoefRuleList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScCoefRuleData[] o = obj.GetCoefRuleList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetResourcePriceData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScResourcePriceData> o = obj.GetResourcePriceData();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTechDetailTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScTechnologyDetailData> o = obj.GetTechDetailTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTechDetailDataByIdLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScTechnologyDetailData o = obj.GetTechDetailDataByIdLevel(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTechCategoryTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScTechnologyCategoryData> o = obj.GetTechCategoryTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBuildLaboratoryTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScBuildLaboratoryData> o = obj.GetBuildLaboratoryTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSlgBuffData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScSlgBuffData o = obj.GetSlgBuffData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSlgBuffTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScSlgBuffData> o = obj.GetSlgBuffTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetItemExchangeData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScItemExchangeData o = obj.GetItemExchangeData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionMonsterData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionMonster o = obj.GetUnionMonsterData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionMonsterTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScUnionMonster> o = obj.GetUnionMonsterTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPveMonsterData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScPveMonsterData o = obj.GetPveMonsterData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetItemExchangeList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScItemExchangeData[] o = obj.GetItemExchangeList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetItemExchangeListData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScItemExchangeListData o = obj.GetItemExchangeListData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBonusFunction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBonusFuncData o = obj.GetBonusFunction(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSettingTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScSettingData> o = obj.GetSettingTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMissionData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScMissionData o = obj.GetMissionData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMilitarytActionData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScMilitarytActionData o = obj.GetMilitarytActionData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMissionTutorialList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScMissionTutorialData[] o = obj.GetMissionTutorialList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetVipDataList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScVipData[] o = obj.GetVipDataList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetVipGiftDataList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScVipGiftData[] o = obj.GetVipGiftDataList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetVipPrivilegeDataList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScVipPrivilege[] o = obj.GetVipPrivilegeDataList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFunctionUnlockText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			string o = obj.GetFunctionUnlockText(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFunctionUnlockLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int o = obj.GetFunctionUnlockLevel(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetResourceRuleDataByTypeLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScResourceRuleData o = obj.GetResourceRuleDataByTypeLevel(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetResourceRuleData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScResourceRuleData o = obj.GetResourceRuleData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMonsterRuleData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScMonsterRuleData o = obj.GetMonsterRuleData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMonsterRuleList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScMonsterRuleData[] o = obj.GetMonsterRuleList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEliteMonsterRuleData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScEliteMonsterRuleData o = obj.GetEliteMonsterRuleData(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActiveConditionData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScActivityConditionData o = obj.GetActiveConditionData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMailCfgData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScMailCfgData o = obj.GetMailCfgData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBasicSurfaceDataByType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScBasicSurfaceData o = obj.GetBasicSurfaceDataByType(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetArtSettingData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScArtSettingData o = obj.GetArtSettingData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetArtSettingList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScArtSettingData[] o = obj.GetArtSettingList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObjectShapeData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScObjectShapeData o = obj.GetObjectShapeData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetObjectShapeList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScObjectShapeData[] o = obj.GetObjectShapeList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetRandomName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			string o = obj.GetRandomName();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSpyPrice(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			string o = obj.GetSpyPrice(arg0, arg1);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLoginData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScLoginData[] o = obj.GetLoginData(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSoldierShowRule(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScShowRule o = obj.GetSoldierShowRule(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionBadgeColorData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionBadgeColorData o = obj.GetUnionBadgeColorData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionBadgeColorList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScUnionBadgeColorData[] o = obj.GetUnionBadgeColorList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionBadgeBorderData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionBadgeBorderData o = obj.GetUnionBadgeBorderData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionBadgeBorderList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScUnionBadgeBorderData[] o = obj.GetUnionBadgeBorderList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionItemData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionItemData o = obj.GetUnionItemData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionBuildingData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionBuildingData o = obj.GetUnionBuildingData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionBuildingList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScUnionBuildingData[] o = obj.GetUnionBuildingList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionMineByResourceType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionBuildingData o = obj.GetUnionMineByResourceType(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionBadgeTotemData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionBadgeTotemData o = obj.GetUnionBadgeTotemData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionBadgeTotemList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScUnionBadgeTotemData[] o = obj.GetUnionBadgeTotemList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionNumByType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			string arg0 = ToLua.CheckString(L, 2);
			int o = obj.GetUnionNumByType(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionLanguageList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScUnionLanguageData[] o = obj.GetUnionLanguageList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionLanguageData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionLanguageData o = obj.GetUnionLanguageData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTradingPostData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScTradingPostData o = obj.GetTradingPostData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionGiftExpData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionGiftExpData o = obj.GetUnionGiftExpData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTradingPostTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScTradingPostData> o = obj.GetTradingPostTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEmbassyTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScEmbassyData> o = obj.GetEmbassyTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEmbassyData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScEmbassyData o = obj.GetEmbassyData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAssembledTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScAssembledData> o = obj.GetAssembledTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetAssembledData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScAssembledData o = obj.GetAssembledData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActMonsterData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScActMonsterId arg0 = (Serclimax.ScActMonsterId)ToLua.CheckObject(L, 2, typeof(Serclimax.ScActMonsterId));
			Serclimax.ScActMonster o = obj.GetActMonsterData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActMonsterRuleData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScActMonsterRule o = obj.GetActMonsterRuleData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTalentTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScTalentData> o = obj.GetTalentTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTalentDataByIdLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScTalentData o = obj.GetTalentDataByIdLevel(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetTalentCategoryTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScTalentCategoryData> o = obj.GetTalentCategoryTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionTechDetailTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScUnionTechData> o = obj.GetUnionTechDetailTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActiveStaticsRule(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScActivityStaticsRuleData> o = obj.GetActiveStaticsRule();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActiveStaticsRuleData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScActivityStaticsRuleData o = obj.GetActiveStaticsRuleData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActiveStaticsList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScActivityStaticsListData> o = obj.GetActiveStaticsList();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActivityStaticsListData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScActivityStaticsListData o = obj.GetActivityStaticsListData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActivityStaticsRewardData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScActivityStaticsRewardData o = obj.GetActivityStaticsRewardData(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActivityStaticsRewardDataById(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScActivityStaticsRewardData o = obj.GetActivityStaticsRewardDataById(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionTechDetailDataByIdLevel(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			Serclimax.ScUnionTechData o = obj.GetUnionTechDetailDataByIdLevel(arg0, arg1);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEquipTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScEquipData> o = obj.GetEquipTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMaterialTable(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScMaterialData> o = obj.GetMaterialTable();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetArmouryData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			System.Collections.Generic.Dictionary<int,Serclimax.ScArmouryData> o = obj.GetArmouryData();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetEquipTextDataByAddition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			string o = obj.GetEquipTextDataByAddition(arg0, arg1);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPVEMoraleBonusFactor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			float o = obj.GetPVEMoraleBonusFactor(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPVEPhysiqueBonusFactor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			float o = obj.GetPVEPhysiqueBonusFactor(arg0);
			LuaDLL.lua_pushnumber(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActivityNoticeList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			Serclimax.ScActivityNoticeData[] o = obj.GetActivityNoticeList();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPassiveSkillData(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(Serclimax.ScTableMgr)))
			{
				Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.ToObject(L, 1);
				System.Collections.Generic.Dictionary<int,Serclimax.ScPassiveSkillData> o = obj.GetPassiveSkillData();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes(L, 1, typeof(Serclimax.ScTableMgr), typeof(int)))
			{
				Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.ToObject(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				Serclimax.ScPassiveSkillData o = obj.GetPassiveSkillData(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Serclimax.ScTableMgr.GetPassiveSkillData");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActivitySiegeMonsterReward(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScActivitySiegeMonsterReward[] o = obj.GetActivitySiegeMonsterReward(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetActivitySiegeMonsterRankRewardByType(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScActivitySiegeMonsterRankReward[] o = obj.GetActivitySiegeMonsterRankRewardByType(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMapBuildingDataByID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScMapBuildingData o = obj.GetMapBuildingDataByID(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetStrongholdRuleByID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScStrongholdRuleData o = obj.GetStrongholdRuleByID(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetFortressRuleByID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScFortressData o = obj.GetFortressRuleByID(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnionOfficialByID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScUnionOfficialData o = obj.GetUnionOfficialByID(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetOfficialByID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScOfficialData o = obj.GetOfficialByID(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMilitaryRankData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScMilitaryRankData o = obj.GetMilitaryRankData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetMobaBuildingRuleData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScMobaBuildingRule o = obj.GetMobaBuildingRuleData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetGuildWarBuildingRuleData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScGuildWarBuildingRule o = obj.GetGuildWarBuildingRuleData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetWorldCityData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)ToLua.CheckObject(L, 1, typeof(Serclimax.ScTableMgr));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			Serclimax.ScWorldCityData o = obj.GetWorldCityData(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_assetbundleLoader(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, Serclimax.ScTableMgr.assetbundleLoader);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ProductionSet(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Serclimax.ScTableMgr obj = (Serclimax.ScTableMgr)o;
			Serclimax.Event.ScDProductionSet ret = obj.ProductionSet;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index ProductionSet on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_assetbundleLoader(IntPtr L)
	{
		try
		{
			Serclimax.AssetbundleLoader arg0 = (Serclimax.AssetbundleLoader)ToLua.CheckObject(L, 2, typeof(Serclimax.AssetbundleLoader));
			Serclimax.ScTableMgr.assetbundleLoader = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

