//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TextManager_LANGUAGEWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(TextManager.LANGUAGE));
		L.RegVar("VN", get_VN, null);
		L.RegVar("EN", get_EN, null);
		// L.RegVar("FR", get_FR, null);
		// L.RegVar("SP", get_SP, null);
		// L.RegVar("PT", get_PT, null);
		// L.RegVar("IT", get_IT, null);
		// L.RegVar("GM", get_GM, null);
		// L.RegVar("RU", get_RU, null);
		// L.RegVar("JP", get_JP, null);
		// L.RegVar("KR", get_KR, null);
		// L.RegVar("TCN", get_TCN, null);
		L.RegVar("NA", get_NA, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VN(IntPtr L)
	{
		ToLua.Push(L, TextManager.LANGUAGE.VN);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EN(IntPtr L)
	{
		ToLua.Push(L, TextManager.LANGUAGE.EN);
		return 1;
	}

	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_FR(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.FR);
	// 	return 1;
	// }
	//
	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_SP(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.SP);
	// 	return 1;
	// }
	//
	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_PT(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.PT);
	// 	return 1;
	// }
	//
	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_IT(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.IT);
	// 	return 1;
	// }
	//
	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_GM(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.GM);
	// 	return 1;
	// }
	//
	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_RU(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.RU);
	// 	return 1;
	// }
	//
	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_JP(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.JP);
	// 	return 1;
	// }
	//
	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_KR(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.KR);
	// 	return 1;
	// }
	//
	// [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	// static int get_TCN(IntPtr L)
	// {
	// 	ToLua.Push(L, TextManager.LANGUAGE.TCN);
	// 	return 1;
	// }

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NA(IntPtr L)
	{
		ToLua.Push(L, TextManager.LANGUAGE.NA);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		TextManager.LANGUAGE o = (TextManager.LANGUAGE)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

