--This file is generated by tools!
--Please do not modify this file!
module("tableData_tSoldierBaptize",package.seeall)
data = {


		[1] = { 

			id = 1,
			ItemComsume = "15019:1",
			GoldConsume = "2:80",
		},
		[2] = { 

			id = 2,
			ItemComsume = "15019:2",
			GoldConsume = "2:160",
		},
		[3] = { 

			id = 3,
			ItemComsume = "15019:3",
			GoldConsume = "2:240",
		},
		[4] = { 

			id = 4,
			ItemComsume = "15019:4",
			GoldConsume = "2:320",
		},
		[5] = { 

			id = 5,
			ItemComsume = "15019:5",
			GoldConsume = "2:400",
		},
		[6] = { 

			id = 6,
			ItemComsume = "15019:6",
			GoldConsume = "2:480",
		},
}
Count=6
