--This file is generated by tools!
--Please do not modify this file!
module("tableData_tAddcoef",package.seeall)
data = {


		[1] = { 

			id = 1,
			MoraleBonusFactor = 0.14,
			PhysiqueBonusFactor = 0.28,
			TenacityBonusFactor = "0",
		},
		[2] = { 

			id = 2,
			MoraleBonusFactor = 0.21,
			PhysiqueBonusFactor = 0.42,
			TenacityBonusFactor = "0",
		},
		[3] = { 

			id = 3,
			MoraleBonusFactor = 0.56,
			PhysiqueBonusFactor = 0.56,
			TenacityBonusFactor = "0",
		},
		[4] = { 

			id = 4,
			MoraleBonusFactor = 0.28,
			PhysiqueBonusFactor = 0.56,
			TenacityBonusFactor = "0",
		},
		[5] = { 

			id = 5,
			MoraleBonusFactor = 0.21,
			PhysiqueBonusFactor = 0.7,
			TenacityBonusFactor = "0",
		},
		[6] = { 

			id = 6,
			MoraleBonusFactor = 0.21,
			PhysiqueBonusFactor = 0.7,
			TenacityBonusFactor = "0",
		},
		[7] = { 

			id = 7,
			MoraleBonusFactor = 0.35,
			PhysiqueBonusFactor = 0.98,
			TenacityBonusFactor = "0",
		},
		[8] = { 

			id = 8,
			MoraleBonusFactor = 0.98,
			PhysiqueBonusFactor = 1.4,
			TenacityBonusFactor = "0",
		},
		[1001] = { 

			id = 1001,
			MoraleBonusFactor = 0.0084,
			PhysiqueBonusFactor = 0.0196,
			TenacityBonusFactor = "0.0105",
		},
		[1002] = { 

			id = 1002,
			MoraleBonusFactor = 0.0112,
			PhysiqueBonusFactor = 0.0147,
			TenacityBonusFactor = "0.0105",
		},
		[1003] = { 

			id = 1003,
			MoraleBonusFactor = 0.0098,
			PhysiqueBonusFactor = 0.0168,
			TenacityBonusFactor = "0.0105",
		},
		[1004] = { 

			id = 1004,
			MoraleBonusFactor = 0.007,
			PhysiqueBonusFactor = 0.0235,
			TenacityBonusFactor = "0.0105",
		},
		[101] = { 

			id = 101,
			MoraleBonusFactor = 0.011,
			PhysiqueBonusFactor = 0.021,
			TenacityBonusFactor = "0.0158",
		},
		[102] = { 

			id = 102,
			MoraleBonusFactor = 0.011,
			PhysiqueBonusFactor = 0.021,
			TenacityBonusFactor = "0.0158",
		},
}
Count=14
