--This file is generated by tools!
--Please do not modify this file!
module("tableData_tMobaRole",package.seeall)
data = {


		[1] = { 

			id = 1,
			Name = "moba_role_1",
			Icon = "Mobaroleselect_1",
			MaxNum = 3,
			RolePrivilege = "50001",
			ScoreAdd = 0,
			SoldierAdd = "",
			description = "moba_roledesc_1;moba_roledesc_2",
		},
		[2] = { 

			id = 2,
			Name = "moba_role_2",
			Icon = "Mobaroleselect_2",
			MaxNum = 3,
			RolePrivilege = "50002",
			ScoreAdd = 0,
			SoldierAdd = "",
			description = "moba_roledesc_3",
		},
		[3] = { 

			id = 3,
			Name = "moba_role_3",
			Icon = "Mobaroleselect_3",
			MaxNum = 3,
			RolePrivilege = "50003",
			ScoreAdd = 0,
			SoldierAdd = "",
			description = "moba_roledesc_4;moba_roledesc_5",
		},
		[4] = { 

			id = 4,
			Name = "moba_role_4",
			Icon = "Mobaroleselect_4",
			MaxNum = 3,
			RolePrivilege = "50004",
			ScoreAdd = 3000,
			SoldierAdd = "",
			description = "moba_roledesc_6",
		},
}
Count=4
