--This file is generated by tools!
--Please do not modify this file!
module("tableData_tActivityShowCongfig",package.seeall)
data = {


		[1001] = { 

			id = 1001,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "title",
			Content = "activity_content_1",
		},
		[1002] = { 

			id = 1002,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "des",
			Content = "activity_content_2",
		},
		[1003] = { 

			id = 1003,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "progress1",
			Content = "activity_content_3",
		},
		[1004] = { 

			id = 1004,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "progress2",
			Content = "activity_content_4",
		},
		[1005] = { 

			id = 1005,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[1006] = { 

			id = 1006,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day1",
			Content = "activity_content_6",
		},
		[1007] = { 

			id = 1007,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day2",
			Content = "activity_content_7",
		},
		[1008] = { 

			id = 1008,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day3",
			Content = "activity_content_8",
		},
		[1009] = { 

			id = 1009,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day4",
			Content = "activity_content_9",
		},
		[1010] = { 

			id = 1010,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day5",
			Content = "activity_content_10",
		},
		[1011] = { 

			id = 1011,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day1tab1",
			Content = "activity_content_22",
		},
		[1012] = { 

			id = 1012,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day1tab2",
			Content = "activity_content_24",
		},
		[1013] = { 

			id = 1013,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day1tab3",
			Content = "activity_content_23",
		},
		[1014] = { 

			id = 1014,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day2tab1",
			Content = "activity_content_12",
		},
		[1015] = { 

			id = 1015,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day2tab2",
			Content = "activity_content_21",
		},
		[1016] = { 

			id = 1016,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day2tab3",
			Content = "activity_content_19",
		},
		[1017] = { 

			id = 1017,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day3tab1",
			Content = "activity_content_16",
		},
		[1018] = { 

			id = 1018,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day3tab2",
			Content = "activity_content_17",
		},
		[1019] = { 

			id = 1019,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day3tab3",
			Content = "activity_content_13",
		},
		[1020] = { 

			id = 1020,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day4tab1",
			Content = "activity_content_14",
		},
		[1021] = { 

			id = 1021,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day4tab2",
			Content = "activity_content_15",
		},
		[1022] = { 

			id = 1022,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day4tab3",
			Content = "activity_content_11",
		},
		[1023] = { 

			id = 1023,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day5tab1",
			Content = "activity_content_18",
		},
		[1024] = { 

			id = 1024,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day5tab2",
			Content = "activity_content_20",
		},
		[1025] = { 

			id = 1025,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "day5tab3",
			Content = "activity_content_25",
		},
		[1026] = { 

			id = 1026,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "error1",
			Content = "KingRoad_Locked",
		},
		[1027] = { 

			id = 1027,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "HelpTitle",
			Content = "activity_content_27",
		},
		[1028] = { 

			id = 1028,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "HelpContent",
			Content = "activity_content_28",
		},
		[1029] = { 

			id = 1029,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "exchangeID",
			Content = "2001;2002;2003;2004;2005;2006;2007;2008;2009",
		},
		[1030] = { 

			id = 1030,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "exchange",
			Content = "activity_content_31",
		},
		[1031] = { 

			id = 1031,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[1032] = { 

			id = 1032,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "elefttime",
			Content = "activity_content_33",
		},
		[1033] = { 

			id = 1033,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[1034] = { 

			id = 1034,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "endtime",
			Content = "activity_content_35",
		},
		[1035] = { 

			id = 1035,
			ActivityID = 1001,
			TempletID = 101,
			ConfigName = "go",
			Content = "mission_go",
		},
		[2001] = { 

			id = 2001,
			ActivityID = 1002,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_55",
		},
		[2002] = { 

			id = 2002,
			ActivityID = 1002,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_30",
		},
		[2003] = { 

			id = 2003,
			ActivityID = 1002,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[2004] = { 

			id = 2004,
			ActivityID = 1002,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_power",
		},
		[2005] = { 

			id = 2005,
			ActivityID = 1002,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[3001] = { 

			id = 3001,
			ActivityID = 1004,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_38",
		},
		[3002] = { 

			id = 3002,
			ActivityID = 1004,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_37",
		},
		[3003] = { 

			id = 3003,
			ActivityID = 1004,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[3004] = { 

			id = 3004,
			ActivityID = 1004,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_baseupgrade",
		},
		[4001] = { 

			id = 4001,
			ActivityID = 1005,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_56",
		},
		[4002] = { 

			id = 4002,
			ActivityID = 1005,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_41",
		},
		[4003] = { 

			id = 4003,
			ActivityID = 1005,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[4004] = { 

			id = 4004,
			ActivityID = 1005,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_union",
		},
		[4005] = { 

			id = 4005,
			ActivityID = 1005,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[4006] = { 

			id = 4006,
			ActivityID = 1005,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[5001] = { 

			id = 5001,
			ActivityID = 1006,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_59",
		},
		[5002] = { 

			id = 5002,
			ActivityID = 1006,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_42",
		},
		[5003] = { 

			id = 5003,
			ActivityID = 1006,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[5004] = { 

			id = 5004,
			ActivityID = 1006,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_speedup",
		},
		[5005] = { 

			id = 5005,
			ActivityID = 1006,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[6001] = { 

			id = 6001,
			ActivityID = 1007,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_57",
		},
		[6002] = { 

			id = 6002,
			ActivityID = 1007,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_51",
		},
		[6003] = { 

			id = 6003,
			ActivityID = 1007,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[6004] = { 

			id = 6004,
			ActivityID = 1007,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_collect",
		},
		[6005] = { 

			id = 6005,
			ActivityID = 1007,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[6006] = { 

			id = 6006,
			ActivityID = 1007,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[7001] = { 

			id = 7001,
			ActivityID = 1008,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_58",
		},
		[7002] = { 

			id = 7002,
			ActivityID = 1008,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_52",
		},
		[7003] = { 

			id = 7003,
			ActivityID = 1008,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[7004] = { 

			id = 7004,
			ActivityID = 1008,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_monster",
		},
		[7005] = { 

			id = 7005,
			ActivityID = 1008,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[7006] = { 

			id = 7006,
			ActivityID = 1008,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[8001] = { 

			id = 8001,
			ActivityID = 3005,
			TempletID = 305,
			ConfigName = "title",
			Content = "RechargeRebate_ui5",
		},
		[8002] = { 

			id = 8002,
			ActivityID = 3005,
			TempletID = 305,
			ConfigName = "des",
			Content = "activity_content_71",
		},
		[8003] = { 

			id = 8003,
			ActivityID = 3005,
			TempletID = 305,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[8004] = { 

			id = 8004,
			ActivityID = 3005,
			TempletID = 305,
			ConfigName = "banner",
			Content = "act_newbie",
		},
		[8005] = { 

			id = 8005,
			ActivityID = 3005,
			TempletID = 305,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[8006] = { 

			id = 8006,
			ActivityID = 3005,
			TempletID = 305,
			ConfigName = "task_name",
			Content = "RechargeRebate_ui7",
		},
		[9001] = { 

			id = 9001,
			ActivityID = 3006,
			TempletID = 306,
			ConfigName = "title",
			Content = "activity_content_62",
		},
		[9002] = { 

			id = 9002,
			ActivityID = 3006,
			TempletID = 306,
			ConfigName = "des",
			Content = "activity_content_47",
		},
		[9003] = { 

			id = 9003,
			ActivityID = 3006,
			TempletID = 306,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[9004] = { 

			id = 9004,
			ActivityID = 3006,
			TempletID = 306,
			ConfigName = "banner",
			Content = "act_consume",
		},
		[9005] = { 

			id = 9005,
			ActivityID = 3006,
			TempletID = 306,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[9006] = { 

			id = 9006,
			ActivityID = 3006,
			TempletID = 306,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[9007] = { 

			id = 9007,
			ActivityID = 3006,
			TempletID = 306,
			ConfigName = "task_name",
			Content = "activity_content_64",
		},
		[10001] = { 

			id = 10001,
			ActivityID = 3007,
			TempletID = 307,
			ConfigName = "title",
			Content = "RechargeRebate_ui6",
		},
		[10002] = { 

			id = 10002,
			ActivityID = 3007,
			TempletID = 307,
			ConfigName = "des",
			Content = "activity_content_71",
		},
		[10003] = { 

			id = 10003,
			ActivityID = 3007,
			TempletID = 307,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[10004] = { 

			id = 10004,
			ActivityID = 3007,
			TempletID = 307,
			ConfigName = "banner",
			Content = "act_dailyRp",
		},
		[10005] = { 

			id = 10005,
			ActivityID = 3007,
			TempletID = 307,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[10006] = { 

			id = 10006,
			ActivityID = 3007,
			TempletID = 307,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[10007] = { 

			id = 10007,
			ActivityID = 3007,
			TempletID = 307,
			ConfigName = "task_name",
			Content = "RechargeRebate_ui8",
		},
		[11001] = { 

			id = 11001,
			ActivityID = 3004,
			TempletID = 604,
			ConfigName = "title",
			Content = "activity_content_53",
		},
		[11002] = { 

			id = 11002,
			ActivityID = 3004,
			TempletID = 604,
			ConfigName = "des",
			Content = "activity_content_54",
		},
		[11003] = { 

			id = 11003,
			ActivityID = 3004,
			TempletID = 604,
			ConfigName = "banner",
			Content = "act_monthcard",
		},
		[11005] = { 

			id = 11005,
			ActivityID = 3004,
			TempletID = 604,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[12001] = { 

			id = 12001,
			ActivityID = 1003,
			TempletID = 103,
			ConfigName = "title",
			Content = "activity_supplycollect_title",
		},
		[12002] = { 

			id = 12002,
			ActivityID = 1003,
			TempletID = 103,
			ConfigName = "rule1",
			Content = "activity_supplyui_tips",
		},
		[12003] = { 

			id = 12003,
			ActivityID = 1003,
			TempletID = 103,
			ConfigName = "rule2",
			Content = "activity_supplyui_tips2",
		},
		[12004] = { 

			id = 12004,
			ActivityID = 1003,
			TempletID = 103,
			ConfigName = "rank",
			Content = "activity_supplyui_rank",
		},
		[12005] = { 

			id = 12005,
			ActivityID = 1003,
			TempletID = 103,
			ConfigName = "HelpTitle",
			Content = "activity_content_27",
		},
		[12006] = { 

			id = 12006,
			ActivityID = 1003,
			TempletID = 103,
			ConfigName = "HelpContent",
			Content = "activity_supplycollect",
		},
		[13001] = { 

			id = 13001,
			ActivityID = 1009,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_65",
		},
		[13002] = { 

			id = 13002,
			ActivityID = 1009,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_51",
		},
		[13003] = { 

			id = 13003,
			ActivityID = 1009,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[13004] = { 

			id = 13004,
			ActivityID = 1009,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_zhandi",
		},
		[13005] = { 

			id = 13005,
			ActivityID = 1009,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[14001] = { 

			id = 14001,
			ActivityID = 1010,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_66",
		},
		[14002] = { 

			id = 14002,
			ActivityID = 1010,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_51",
		},
		[14003] = { 

			id = 14003,
			ActivityID = 1010,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[14004] = { 

			id = 14004,
			ActivityID = 1010,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_collect",
		},
		[14005] = { 

			id = 14005,
			ActivityID = 1010,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[14006] = { 

			id = 14006,
			ActivityID = 1010,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[15001] = { 

			id = 15001,
			ActivityID = 1011,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_67",
		},
		[15002] = { 

			id = 15002,
			ActivityID = 1011,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_51",
		},
		[15003] = { 

			id = 15003,
			ActivityID = 1011,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[15004] = { 

			id = 15004,
			ActivityID = 1011,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_zhandi",
		},
		[15005] = { 

			id = 15005,
			ActivityID = 1011,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[16001] = { 

			id = 16001,
			ActivityID = 1012,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_68",
		},
		[16002] = { 

			id = 16002,
			ActivityID = 1012,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_51",
		},
		[16003] = { 

			id = 16003,
			ActivityID = 1012,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[16004] = { 

			id = 16004,
			ActivityID = 1012,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_collect",
		},
		[16005] = { 

			id = 16005,
			ActivityID = 1012,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[16006] = { 

			id = 16006,
			ActivityID = 1012,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[17001] = { 

			id = 17001,
			ActivityID = 1013,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_69",
		},
		[17002] = { 

			id = 17002,
			ActivityID = 1013,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_51",
		},
		[17003] = { 

			id = 17003,
			ActivityID = 1013,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[17004] = { 

			id = 17004,
			ActivityID = 1013,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_zhandi",
		},
		[17005] = { 

			id = 17005,
			ActivityID = 1013,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[18001] = { 

			id = 18001,
			ActivityID = 1014,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_70",
		},
		[18002] = { 

			id = 18002,
			ActivityID = 1014,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_51",
		},
		[18003] = { 

			id = 18003,
			ActivityID = 1014,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[18004] = { 

			id = 18004,
			ActivityID = 1014,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_zhandi",
		},
		[18005] = { 

			id = 18005,
			ActivityID = 1014,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[19001] = { 

			id = 19001,
			ActivityID = 7000,
			TempletID = 608,
			ConfigName = "title",
			Content = "Hero_WeekCard_ui1",
		},
		[19002] = { 

			id = 19002,
			ActivityID = 7000,
			TempletID = 608,
			ConfigName = "des",
			Content = "activity_content_72",
		},
		[19003] = { 

			id = 19003,
			ActivityID = 7000,
			TempletID = 608,
			ConfigName = "banner",
			Content = "act_HeroWeekCard",
		},
		[19004] = { 

			id = 19004,
			ActivityID = 7000,
			TempletID = 608,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[19005] = { 

			id = 19005,
			ActivityID = 3008,
			TempletID = 609,
			ConfigName = "title",
			Content = "Union_Mcard",
		},
		[19006] = { 

			id = 19006,
			ActivityID = 3008,
			TempletID = 609,
			ConfigName = "des",
			Content = "Union_Mcard_ui1",
		},
		[19007] = { 

			id = 19007,
			ActivityID = 3008,
			TempletID = 609,
			ConfigName = "banner",
			Content = "act_monthcard",
		},
		[19008] = { 

			id = 19008,
			ActivityID = 3008,
			TempletID = 609,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[20001] = { 

			id = 20001,
			ActivityID = 3017,
			TempletID = 309,
			ConfigName = "title",
			Content = "TotalCost_ui1",
		},
		[20002] = { 

			id = 20002,
			ActivityID = 3017,
			TempletID = 309,
			ConfigName = "des",
			Content = "activity_content_73",
		},
		[20003] = { 

			id = 20003,
			ActivityID = 3017,
			TempletID = 309,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20004] = { 

			id = 20004,
			ActivityID = 3017,
			TempletID = 309,
			ConfigName = "banner",
			Content = "act_newbie",
		},
		[20005] = { 

			id = 20005,
			ActivityID = 3017,
			TempletID = 309,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20006] = { 

			id = 20006,
			ActivityID = 3017,
			TempletID = 309,
			ConfigName = "task_name",
			Content = "TotalCost_ui1",
		},
		[20007] = { 

			id = 20007,
			ActivityID = 1200,
			TempletID = 112,
			ConfigName = "HelpTitle",
			Content = "activity_content_27",
		},
		[20008] = { 

			id = 20008,
			ActivityID = 1200,
			TempletID = 112,
			ConfigName = "HelpContent",
			Content = "activity_zq_desc1",
		},
		[20009] = { 

			id = 20009,
			ActivityID = 1200,
			TempletID = 112,
			ConfigName = "title",
			Content = "activity_zq_desc2",
		},
		[20010] = { 

			id = 20010,
			ActivityID = 1201,
			TempletID = 112,
			ConfigName = "HelpTitle",
			Content = "activity_content_27",
		},
		[20011] = { 

			id = 20011,
			ActivityID = 1201,
			TempletID = 112,
			ConfigName = "HelpContent",
			Content = "activity_content_80",
		},
		[20012] = { 

			id = 20012,
			ActivityID = 1201,
			TempletID = 112,
			ConfigName = "title",
			Content = "activity_content_79",
		},
		[20013] = { 

			id = 20013,
			ActivityID = 3018,
			TempletID = 309,
			ConfigName = "title",
			Content = "TotalCost_ui1",
		},
		[20014] = { 

			id = 20014,
			ActivityID = 3018,
			TempletID = 309,
			ConfigName = "des",
			Content = "activity_content_73",
		},
		[20015] = { 

			id = 20015,
			ActivityID = 3018,
			TempletID = 309,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20016] = { 

			id = 20016,
			ActivityID = 3018,
			TempletID = 309,
			ConfigName = "banner",
			Content = "act_newbie",
		},
		[20017] = { 

			id = 20017,
			ActivityID = 3018,
			TempletID = 309,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20018] = { 

			id = 20018,
			ActivityID = 3018,
			TempletID = 309,
			ConfigName = "task_name",
			Content = "TotalCost_ui1",
		},
		[20019] = { 

			id = 20019,
			ActivityID = 1015,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_zq_title",
		},
		[20020] = { 

			id = 20020,
			ActivityID = 1015,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_zq_desc",
		},
		[20021] = { 

			id = 20021,
			ActivityID = 1015,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20022] = { 

			id = 20022,
			ActivityID = 1015,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_zq",
		},
		[20023] = { 

			id = 20023,
			ActivityID = 1015,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20024] = { 

			id = 20024,
			ActivityID = 1015,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[20025] = { 

			id = 20025,
			ActivityID = 1202,
			TempletID = 112,
			ConfigName = "HelpTitle",
			Content = "activity_content_27",
		},
		[20026] = { 

			id = 20026,
			ActivityID = 1202,
			TempletID = 112,
			ConfigName = "HelpContent",
			Content = "activity_zq_desc3",
		},
		[20027] = { 

			id = 20027,
			ActivityID = 1202,
			TempletID = 112,
			ConfigName = "title",
			Content = "activity_zq_desc4",
		},
		[20028] = { 

			id = 20028,
			ActivityID = 3019,
			TempletID = 309,
			ConfigName = "title",
			Content = "TotalCost_ui1",
		},
		[20029] = { 

			id = 20029,
			ActivityID = 3019,
			TempletID = 309,
			ConfigName = "des",
			Content = "activity_content_73",
		},
		[20030] = { 

			id = 20030,
			ActivityID = 3019,
			TempletID = 309,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20031] = { 

			id = 20031,
			ActivityID = 3019,
			TempletID = 309,
			ConfigName = "banner",
			Content = "act_newbie",
		},
		[20032] = { 

			id = 20032,
			ActivityID = 3019,
			TempletID = 309,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20033] = { 

			id = 20033,
			ActivityID = 3019,
			TempletID = 309,
			ConfigName = "task_name",
			Content = "TotalCost_ui1",
		},
		[20034] = { 

			id = 20034,
			ActivityID = 3020,
			TempletID = 309,
			ConfigName = "title",
			Content = "TotalCost_ui1",
		},
		[20035] = { 

			id = 20035,
			ActivityID = 3020,
			TempletID = 309,
			ConfigName = "des",
			Content = "activity_content_73",
		},
		[20036] = { 

			id = 20036,
			ActivityID = 3020,
			TempletID = 309,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20037] = { 

			id = 20037,
			ActivityID = 3020,
			TempletID = 309,
			ConfigName = "banner",
			Content = "act_newbie",
		},
		[20038] = { 

			id = 20038,
			ActivityID = 3020,
			TempletID = 309,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20039] = { 

			id = 20039,
			ActivityID = 3020,
			TempletID = 309,
			ConfigName = "task_name",
			Content = "TotalCost_ui1",
		},
		[20040] = { 

			id = 20040,
			ActivityID = 3021,
			TempletID = 307,
			ConfigName = "title",
			Content = "RechargeRebate_ui6",
		},
		[20041] = { 

			id = 20041,
			ActivityID = 3021,
			TempletID = 307,
			ConfigName = "des",
			Content = "activity_content_71",
		},
		[20042] = { 

			id = 20042,
			ActivityID = 3021,
			TempletID = 307,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20043] = { 

			id = 20043,
			ActivityID = 3021,
			TempletID = 307,
			ConfigName = "banner",
			Content = "act_dailyRp",
		},
		[20044] = { 

			id = 20044,
			ActivityID = 3021,
			TempletID = 307,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20045] = { 

			id = 20045,
			ActivityID = 3021,
			TempletID = 307,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[20046] = { 

			id = 20046,
			ActivityID = 3021,
			TempletID = 307,
			ConfigName = "task_name",
			Content = "RechargeRebate_ui8",
		},
		[20047] = { 

			id = 20047,
			ActivityID = 3022,
			TempletID = 307,
			ConfigName = "title",
			Content = "RechargeRebate_ui6",
		},
		[20048] = { 

			id = 20048,
			ActivityID = 3022,
			TempletID = 307,
			ConfigName = "des",
			Content = "activity_content_71",
		},
		[20049] = { 

			id = 20049,
			ActivityID = 3022,
			TempletID = 307,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20050] = { 

			id = 20050,
			ActivityID = 3022,
			TempletID = 307,
			ConfigName = "banner",
			Content = "act_dailyRp",
		},
		[20051] = { 

			id = 20051,
			ActivityID = 3022,
			TempletID = 307,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20052] = { 

			id = 20052,
			ActivityID = 3022,
			TempletID = 307,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[20053] = { 

			id = 20053,
			ActivityID = 3022,
			TempletID = 307,
			ConfigName = "task_name",
			Content = "RechargeRebate_ui8",
		},
		[20054] = { 

			id = 20054,
			ActivityID = 3023,
			TempletID = 305,
			ConfigName = "title",
			Content = "Act_Left_Btn_Text2",
		},
		[20055] = { 

			id = 20055,
			ActivityID = 3023,
			TempletID = 305,
			ConfigName = "des",
			Content = "activity_content_71",
		},
		[20056] = { 

			id = 20056,
			ActivityID = 3023,
			TempletID = 305,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20057] = { 

			id = 20057,
			ActivityID = 3023,
			TempletID = 305,
			ConfigName = "banner",
			Content = "act_newbie",
		},
		[20058] = { 

			id = 20058,
			ActivityID = 3023,
			TempletID = 305,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20059] = { 

			id = 20059,
			ActivityID = 3023,
			TempletID = 305,
			ConfigName = "task_name",
			Content = "RechargeRebate_ui7",
		},
		[20060] = { 

			id = 20060,
			ActivityID = 3024,
			TempletID = 307,
			ConfigName = "title",
			Content = "RechargeRebate_ui6",
		},
		[20061] = { 

			id = 20061,
			ActivityID = 3024,
			TempletID = 307,
			ConfigName = "des",
			Content = "activity_content_71",
		},
		[20062] = { 

			id = 20062,
			ActivityID = 3024,
			TempletID = 307,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20063] = { 

			id = 20063,
			ActivityID = 3024,
			TempletID = 307,
			ConfigName = "banner",
			Content = "act_dailyRp",
		},
		[20064] = { 

			id = 20064,
			ActivityID = 3024,
			TempletID = 307,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20065] = { 

			id = 20065,
			ActivityID = 3024,
			TempletID = 307,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[20066] = { 

			id = 20066,
			ActivityID = 3024,
			TempletID = 307,
			ConfigName = "task_name",
			Content = "RechargeRebate_ui8",
		},
		[20070] = { 

			id = 20070,
			ActivityID = 1016,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_83",
		},
		[20071] = { 

			id = 20071,
			ActivityID = 1016,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_84",
		},
		[20072] = { 

			id = 20072,
			ActivityID = 1016,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20073] = { 

			id = 20073,
			ActivityID = 1016,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_power",
		},
		[20074] = { 

			id = 20074,
			ActivityID = 1016,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20075] = { 

			id = 20075,
			ActivityID = 1016,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[20076] = { 

			id = 20076,
			ActivityID = 1204,
			TempletID = 112,
			ConfigName = "HelpTitle",
			Content = "activity_content_xmas",
		},
		[20077] = { 

			id = 20077,
			ActivityID = 1204,
			TempletID = 112,
			ConfigName = "HelpContent",
			Content = "activity_xmas_desc1",
		},
		[20078] = { 

			id = 20078,
			ActivityID = 1204,
			TempletID = 112,
			ConfigName = "title",
			Content = "activity_xmas_desc2",
		},
		[20079] = { 

			id = 20079,
			ActivityID = 1204,
			TempletID = 112,
			ConfigName = "banner",
			Content = "act_xmas",
		},
		[20148] = { 

			id = 20148,
			ActivityID = 1401,
			TempletID = 140,
			ConfigName = "title",
			Content = "activity_content_94",
		},
		[20149] = { 

			id = 20149,
			ActivityID = 1401,
			TempletID = 140,
			ConfigName = "des",
			Content = "activity_content_88",
		},
		[20150] = { 

			id = 20150,
			ActivityID = 1401,
			TempletID = 140,
			ConfigName = "banner",
			Content = "act_baseupgrade",
		},
		[20151] = { 

			id = 20151,
			ActivityID = 1401,
			TempletID = 140,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20152] = { 

			id = 20152,
			ActivityID = 30332,
			TempletID = 309,
			ConfigName = "title",
			Content = "TotalCost_ui1",
		},
		[20153] = { 

			id = 20153,
			ActivityID = 30332,
			TempletID = 309,
			ConfigName = "des",
			Content = "activity_content_73",
		},
		[20154] = { 

			id = 20154,
			ActivityID = 30332,
			TempletID = 309,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20155] = { 

			id = 20155,
			ActivityID = 30332,
			TempletID = 309,
			ConfigName = "banner",
			Content = "act_newbie",
		},
		[20156] = { 

			id = 20156,
			ActivityID = 30332,
			TempletID = 309,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20157] = { 

			id = 20157,
			ActivityID = 30332,
			TempletID = 309,
			ConfigName = "task_name",
			Content = "TotalCost_ui1",
		},
		[20201] = { 

			id = 20201,
			ActivityID = 1017,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_96",
		},
		[20202] = { 

			id = 20202,
			ActivityID = 1017,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_97",
		},
		[20203] = { 

			id = 20203,
			ActivityID = 1017,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20204] = { 

			id = 20204,
			ActivityID = 1017,
			TempletID = 102,
			ConfigName = "banner",
			Content = "ac_all03new",
		},
		[20206] = { 

			id = 20206,
			ActivityID = 1017,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[20301] = { 

			id = 20301,
			ActivityID = 1018,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_98",
		},
		[20302] = { 

			id = 20302,
			ActivityID = 1018,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_101",
		},
		[20303] = { 

			id = 20303,
			ActivityID = 1018,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20304] = { 

			id = 20304,
			ActivityID = 1018,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_chouka",
		},
		[20305] = { 

			id = 20305,
			ActivityID = 1018,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20401] = { 

			id = 20401,
			ActivityID = 1019,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_99",
		},
		[20402] = { 

			id = 20402,
			ActivityID = 1019,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_102",
		},
		[20403] = { 

			id = 20403,
			ActivityID = 1019,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20404] = { 

			id = 20404,
			ActivityID = 1019,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_judian",
		},
		[20405] = { 

			id = 20405,
			ActivityID = 1019,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20406] = { 

			id = 20406,
			ActivityID = 1019,
			TempletID = 102,
			ConfigName = "refreshtime",
			Content = "activity_content_34",
		},
		[20501] = { 

			id = 20501,
			ActivityID = 1020,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_100",
		},
		[20502] = { 

			id = 20502,
			ActivityID = 1020,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_103",
		},
		[20503] = { 

			id = 20503,
			ActivityID = 1020,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20504] = { 

			id = 20504,
			ActivityID = 1020,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_zhanhun",
		},
		[20505] = { 

			id = 20505,
			ActivityID = 1020,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
		[20601] = { 

			id = 20601,
			ActivityID = 1031,
			TempletID = 102,
			ConfigName = "title",
			Content = "activity_content_99",
		},
		[20602] = { 

			id = 20602,
			ActivityID = 1031,
			TempletID = 102,
			ConfigName = "des",
			Content = "activity_content_102",
		},
		[20603] = { 

			id = 20603,
			ActivityID = 1031,
			TempletID = 102,
			ConfigName = "progress3",
			Content = "activity_content_5",
		},
		[20604] = { 

			id = 20604,
			ActivityID = 1031,
			TempletID = 102,
			ConfigName = "banner",
			Content = "act_judian",
		},
		[20605] = { 

			id = 20605,
			ActivityID = 1031,
			TempletID = 102,
			ConfigName = "lefttime",
			Content = "activity_content_32",
		},
}
Count=249
