--This file is generated by tools!
--Please do not modify this file!
module("tableData_tIAPChange",package.seeall)
data = {


		[200] = { 

			id = 200,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[204] = { 

			id = 204,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[205] = { 

			id = 205,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[206] = { 

			id = 206,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[207] = { 

			id = 207,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[208] = { 

			id = 208,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[209] = { 

			id = 209,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[612] = { 

			id = 612,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[613] = { 

			id = 613,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[614] = { 

			id = 614,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[615] = { 

			id = 615,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[616] = { 

			id = 616,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[622] = { 

			id = 622,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[623] = { 

			id = 623,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[624] = { 

			id = 624,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[625] = { 

			id = 625,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[626] = { 

			id = 626,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[107] = { 

			id = 107,
			vipMinLevel = 5,
			vipMaxLevel = 15,
		},
		[108] = { 

			id = 108,
			vipMinLevel = 5,
			vipMaxLevel = 15,
		},
		[109] = { 

			id = 109,
			vipMinLevel = 10,
			vipMaxLevel = 15,
		},
		[101] = { 

			id = 101,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[102] = { 

			id = 102,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[103] = { 

			id = 103,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[104] = { 

			id = 104,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[105] = { 

			id = 105,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[106] = { 

			id = 106,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[300] = { 

			id = 300,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[400] = { 

			id = 400,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[500] = { 

			id = 500,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[701] = { 

			id = 701,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[702] = { 

			id = 702,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[703] = { 

			id = 703,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[704] = { 

			id = 704,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[801] = { 

			id = 801,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
		[901] = { 

			id = 901,
			vipMinLevel = 0,
			vipMaxLevel = 0,
		},
}
Count=35
