--This file is generated by tools!
--Please do not modify this file!
module("tableData_tUnionLanguage",package.seeall)
data = {


		[1] = { 

			id = 1,
			language = "setting_language_en",
			icon = "en",
		},
		[2] = { 

			id = 2,
			language = "setting_language_fr",
			icon = "fr",
		},
		[0] = { 

			id = 0,
			language = "setting_language_cn",
			icon = "cn",
		},
		[10] = { 

			id = 10,
			language = "setting_language_tcn",
			icon = "td",
		},
		[5] = { 

			id = 5,
			language = "setting_language_it",
			icon = "it",
		},
		[3] = { 

			id = 3,
			language = "setting_language_sp",
			icon = "sp",
		},
		[4] = { 

			id = 4,
			language = "setting_language_pt",
			icon = "pt",
		},
		[6] = { 

			id = 6,
			language = "setting_language_gm",
			icon = "gm",
		},
		[7] = { 

			id = 7,
			language = "setting_language_ru",
			icon = "ru",
		},
		[8] = { 

			id = 8,
			language = "setting_language_jp",
			icon = "jp",
		},
		[9] = { 

			id = 9,
			language = "setting_language_kr",
			icon = "kr",
		},
		[11] = { 

			id = 11,
			language = "setting_language_ind",
			icon = "Indonesia",
		},
		[12] = { 

			id = 12,
			language = "setting_language_mal",
			icon = "Malaysia",
		},
		[13] = { 

			id = 13,
			language = "setting_language_phi",
			icon = "Philippines",
		},
		[14] = { 

			id = 14,
			language = "setting_language_sin",
			icon = "Singapore",
		},
		[15] = { 

			id = 15,
			language = "setting_language_tha",
			icon = "Thailand",
		},
		[16] = { 

			id = 16,
			language = "setting_language_tun",
			icon = "TUN",
		},
		[17] = { 

			id = 17,
			language = "setting_language_vie",
			icon = "Vietnam",
		},
}
Count=18
