--This file is generated by tools!
--Please do not modify this file!
module("tableData_tAttributeExchange",package.seeall)
data = {


		[1027] = { 

			id = 1027,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1025] = { 

			id = 1025,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1004] = { 

			id = 1004,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1005] = { 

			id = 1005,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1006] = { 

			id = 1006,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1008] = { 

			id = 1008,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1029] = { 

			id = 1029,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1031] = { 

			id = 1031,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1033] = { 

			id = 1033,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1035] = { 

			id = 1035,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1092] = { 

			id = 1092,
			coef101 = 0,
			coef102 = 0.1,
		},
		[1037] = { 

			id = 1037,
			coef101 = 0,
			coef102 = 0.1,
		},
		[22] = { 

			id = 22,
			coef101 = 0.1,
			coef102 = 0,
		},
		[23] = { 

			id = 23,
			coef101 = 0.1,
			coef102 = 0,
		},
		[2] = { 

			id = 2,
			coef101 = 0.1,
			coef102 = 0,
		},
		[5] = { 

			id = 5,
			coef101 = 0.1,
			coef102 = 0,
		},
		[9] = { 

			id = 9,
			coef101 = 0.1,
			coef102 = 0,
		},
}
Count=17
