--This file is generated by tools!
--Please do not modify this file!
module("tableData_tPVPATK",package.seeall)
data = {


		[101] = { 

			id = 101,
			name = "PVP_ATK_Activity_ui9",
			type = 1,
			rules = "101;102;103;104;105;106;107;108",
			personal = 21,
			no1 = 961601,
			no2 = 961602,
			no3 = 961603,
			no4 = 961604,
			no5 = 961605,
			no6 = 961606,
			no7 = 961607,
			show1 = 961601,
			show2 = 961602,
			show3 = 961603,
			show4 = 961604,
			show5 = 961605,
			show6 = 961606,
			show7 = 961607,
		},
}
Count=1
