--This file is generated by tools!
--Please do not modify this file!
module("tableData_tFortressRule",package.seeall)
data = {


		[1] = { 

			id = 1,
			BuildId = 1301,
			Xcoord = 113,
			Ycoord = 174,
			SurfaceType = "9",
			name = "Duke_15",
			Locktype = 1,
			SurfaceID = 28,
			UnionBuff = "1504",
			DayDrop = 6205,
			MergeLocktype = 1,
			SoldierLevelup = "1001:2",
			SoldierNum = "1;750",
		},
		[2] = { 

			id = 2,
			BuildId = 1302,
			Xcoord = 174,
			Ycoord = 129,
			SurfaceType = "9",
			name = "Duke_16",
			Locktype = 0,
			SurfaceID = 29,
			UnionBuff = "1501",
			DayDrop = 6207,
			MergeLocktype = 1,
			SoldierLevelup = "1004:2",
			SoldierNum = "1;750",
		},
		[3] = { 

			id = 3,
			BuildId = 1303,
			Xcoord = 236,
			Ycoord = 175,
			SurfaceType = "9",
			name = "Duke_17",
			Locktype = 0,
			SurfaceID = 30,
			UnionBuff = "1504",
			DayDrop = 6205,
			MergeLocktype = 0,
			SoldierLevelup = "1002:2",
			SoldierNum = "1;750",
		},
		[4] = { 

			id = 4,
			BuildId = 1304,
			Xcoord = 175,
			Ycoord = 220,
			SurfaceType = "9",
			name = "Duke_18",
			Locktype = 0,
			SurfaceID = 31,
			UnionBuff = "1501",
			DayDrop = 6207,
			MergeLocktype = 0,
			SoldierLevelup = "1003:2",
			SoldierNum = "1;750",
		},
}
Count=4
