--This file is generated by tools!
--Please do not modify this file!
module("tableData_tObjectSharp",package.seeall)
data = {


		[4] = { 

			id = 4,
			xMin = 0,
			xMax = 1,
			yMin = 0,
			yMax = 1,
		},
		[9] = { 

			id = 9,
			xMin = -1,
			xMax = 1,
			yMin = -1,
			yMax = 1,
		},
		[2] = { 

			id = 2,
			xMin = 0,
			xMax = 1,
			yMin = 0,
			yMax = 0,
		},
		[16] = { 

			id = 16,
			xMin = -1,
			xMax = 2,
			yMin = -1,
			yMax = 2,
		},
		[17] = { 

			id = 17,
			xMin = 0,
			xMax = 3,
			yMin = 0,
			yMax = 3,
		},
		[49] = { 

			id = 49,
			xMin = -3,
			xMax = 3,
			yMin = -3,
			yMax = 3,
		},
}
Count=6
