--This file is generated by tools!
--Please do not modify this file!
module("tableData_tSkin",package.seeall)
data = {


		[6000] = { 

			id = 6000,
			SkinType = 1,
			MapArt = 0,
			SkinLabel = 0,
			SkinAttribute = "",
			SkinPower = 0,
			GetType = "",
			Icon = "",
			RankNeed = 0,
		},
		[6001] = { 

			id = 6001,
			SkinType = 2,
			MapArt = 901,
			SkinLabel = 0,
			SkinAttribute = "10000,5,2;10000,2,2",
			SkinPower = 2000,
			GetType = "ui_moba_143",
			Icon = "skin_901",
			RankNeed = 1,
		},
		[6002] = { 

			id = 6002,
			SkinType = 2,
			MapArt = 901,
			SkinLabel = 0,
			SkinAttribute = "10000,5,4;10000,2,4",
			SkinPower = 4000,
			GetType = "ui_moba_143",
			Icon = "skin_901",
			RankNeed = 2,
		},
		[6003] = { 

			id = 6003,
			SkinType = 2,
			MapArt = 903,
			SkinLabel = 0,
			SkinAttribute = "10000,5,6;10000,2,6",
			SkinPower = 6000,
			GetType = "ui_moba_143",
			Icon = "skin_903",
			RankNeed = 3,
		},
		[6004] = { 

			id = 6004,
			SkinType = 2,
			MapArt = 903,
			SkinLabel = 0,
			SkinAttribute = "10000,5,9;10000,2,9",
			SkinPower = 9000,
			GetType = "ui_moba_143",
			Icon = "skin_903",
			RankNeed = 4,
		},
		[6005] = { 

			id = 6005,
			SkinType = 2,
			MapArt = 902,
			SkinLabel = 0,
			SkinAttribute = "10000,5,12;10000,2,12",
			SkinPower = 12000,
			GetType = "ui_moba_143",
			Icon = "skin_902",
			RankNeed = 5,
		},
		[6006] = { 

			id = 6006,
			SkinType = 2,
			MapArt = 902,
			SkinLabel = 0,
			SkinAttribute = "10000,5,15;10000,2,15",
			SkinPower = 15000,
			GetType = "ui_moba_143",
			Icon = "skin_902",
			RankNeed = 6,
		},
		[6007] = { 

			id = 6007,
			SkinType = 2,
			MapArt = 905,
			SkinLabel = 0,
			SkinAttribute = "10000,5,18;10000,2,18",
			SkinPower = 18000,
			GetType = "ui_moba_143",
			Icon = "skin_905",
			RankNeed = 7,
		},
		[6008] = { 

			id = 6008,
			SkinType = 2,
			MapArt = 908,
			SkinLabel = 0,
			SkinAttribute = "10000,5,21;10000,2,21",
			SkinPower = 21000,
			GetType = "ui_moba_143",
			Icon = "skin_908",
			RankNeed = 8,
		},
		[6009] = { 

			id = 6009,
			SkinType = 2,
			MapArt = 904,
			SkinLabel = 0,
			SkinAttribute = "10000,5,25;10000,2,25",
			SkinPower = 25000,
			GetType = "ui_moba_143",
			Icon = "skin_904",
			RankNeed = 9,
		},
		[6010] = { 

			id = 6010,
			SkinType = 2,
			MapArt = 909,
			SkinLabel = 0,
			SkinAttribute = "10000,5,30;10000,2,30",
			SkinPower = 30000,
			GetType = "ui_moba_143",
			Icon = "skin_909",
			RankNeed = 10,
		},
		[6011] = { 

			id = 6011,
			SkinType = 3,
			MapArt = 910,
			SkinLabel = 0,
			SkinAttribute = "10000,5,15;10000,2,15",
			SkinPower = 15000,
			GetType = "ui_unionwar_43",
			Icon = "skin_910",
			RankNeed = 0,
		},
		[6012] = { 

			id = 6012,
			SkinType = 4,
			MapArt = 906,
			SkinLabel = 0,
			SkinAttribute = "10000,5,15;10000,2,15",
			SkinPower = 15000,
			GetType = "activity_content_87",
			Icon = "skin_906",
			RankNeed = 0,
		},
		[6013] = { 

			id = 6013,
			SkinType = 5,
			MapArt = 907,
			SkinLabel = 0,
			SkinAttribute = "10000,5,3;10000,2,3",
			SkinPower = 3000,
			GetType = "hero_equip_23",
			Icon = "skin_907",
			RankNeed = 0,
		},
}
Count=14
