--This file is generated by tools!
--Please do not modify this file!
module("tableData_tActivityForecast",package.seeall)
data = {


		[2012] = { 

			id = 2012,
			order = 1000,
			title = "stronghold_1",
			image = "activity_stronghold",
			text1 = "RebelArmyAttack_ui2",
			text2 = "activity_stronghold1",
		},
		[2013] = { 

			id = 2013,
			order = 2000,
			title = "Duke_7",
			image = "activity_stronghold",
			text1 = "RebelArmyAttack_ui2",
			text2 = "activity_fortress1",
		},
}
Count=2
