--This file is generated by tools!
--Please do not modify this file!
module("tableData_tUnionBadgeTotem",package.seeall)
data = {


		[1] = { 

			id = 1,
			icon = "totem1",
		},
		[2] = { 

			id = 2,
			icon = "totem2",
		},
		[3] = { 

			id = 3,
			icon = "totem3",
		},
		[4] = { 

			id = 4,
			icon = "totem4",
		},
		[5] = { 

			id = 5,
			icon = "totem5",
		},
		[6] = { 

			id = 6,
			icon = "totem6",
		},
		[7] = { 

			id = 7,
			icon = "totem7",
		},
		[8] = { 

			id = 8,
			icon = "totem8",
		},
		[9] = { 

			id = 9,
			icon = "totem9",
		},
		[10] = { 

			id = 10,
			icon = "totem10",
		},
		[11] = { 

			id = 11,
			icon = "totem11",
		},
		[12] = { 

			id = 12,
			icon = "totem12",
		},
		[13] = { 

			id = 13,
			icon = "totem13",
		},
		[14] = { 

			id = 14,
			icon = "totem14",
		},
		[15] = { 

			id = 15,
			icon = "totem15",
		},
		[16] = { 

			id = 16,
			icon = "totem16",
		},
		[17] = { 

			id = 17,
			icon = "totem17",
		},
		[18] = { 

			id = 18,
			icon = "totem18",
		},
		[19] = { 

			id = 19,
			icon = "totem19",
		},
		[20] = { 

			id = 20,
			icon = "totem20",
		},
		[21] = { 

			id = 21,
			icon = "totem21",
		},
}
Count=21
