--This file is generated by tools!
--Please do not modify this file!
module("tableData_tTradingPost",package.seeall)
data = {


		[1] = { 

			id = 1,
			labId = 41,
			buildLevel = 1,
			addPower = 12,
			rate = 35,
			resNum = 7500,
			speedUp = 0,
		},
		[2] = { 

			id = 2,
			labId = 41,
			buildLevel = 2,
			addPower = 33,
			rate = 34.5,
			resNum = 15000,
			speedUp = 0,
		},
		[3] = { 

			id = 3,
			labId = 41,
			buildLevel = 3,
			addPower = 59,
			rate = 34,
			resNum = 30000,
			speedUp = 0,
		},
		[4] = { 

			id = 4,
			labId = 41,
			buildLevel = 4,
			addPower = 91,
			rate = 33.5,
			resNum = 45000,
			speedUp = 0,
		},
		[5] = { 

			id = 5,
			labId = 41,
			buildLevel = 5,
			addPower = 130,
			rate = 33,
			resNum = 75000,
			speedUp = 0,
		},
		[6] = { 

			id = 6,
			labId = 41,
			buildLevel = 6,
			addPower = 188,
			rate = 32.5,
			resNum = 112500,
			speedUp = 0,
		},
		[7] = { 

			id = 7,
			labId = 41,
			buildLevel = 7,
			addPower = 258,
			rate = 32,
			resNum = 150000,
			speedUp = 0,
		},
		[8] = { 

			id = 8,
			labId = 41,
			buildLevel = 8,
			addPower = 341,
			rate = 31.5,
			resNum = 180000,
			speedUp = 0,
		},
		[9] = { 

			id = 9,
			labId = 41,
			buildLevel = 9,
			addPower = 442,
			rate = 31,
			resNum = 225000,
			speedUp = 0,
		},
		[10] = { 

			id = 10,
			labId = 41,
			buildLevel = 10,
			addPower = 607,
			rate = 30.5,
			resNum = 270000,
			speedUp = 0,
		},
		[11] = { 

			id = 11,
			labId = 41,
			buildLevel = 11,
			addPower = 881,
			rate = 30,
			resNum = 315000,
			speedUp = 0,
		},
		[12] = { 

			id = 12,
			labId = 41,
			buildLevel = 12,
			addPower = 1305,
			rate = 29,
			resNum = 375000,
			speedUp = 0,
		},
		[13] = { 

			id = 13,
			labId = 41,
			buildLevel = 13,
			addPower = 1965,
			rate = 28,
			resNum = 450000,
			speedUp = 0,
		},
		[14] = { 

			id = 14,
			labId = 41,
			buildLevel = 14,
			addPower = 2969,
			rate = 27,
			resNum = 525000,
			speedUp = 0,
		},
		[15] = { 

			id = 15,
			labId = 41,
			buildLevel = 15,
			addPower = 4529,
			rate = 26,
			resNum = 600000,
			speedUp = 0,
		},
		[16] = { 

			id = 16,
			labId = 41,
			buildLevel = 16,
			addPower = 6937,
			rate = 25,
			resNum = 750000,
			speedUp = 0,
		},
		[17] = { 

			id = 17,
			labId = 41,
			buildLevel = 17,
			addPower = 10566,
			rate = 24,
			resNum = 900000,
			speedUp = 0,
		},
		[18] = { 

			id = 18,
			labId = 41,
			buildLevel = 18,
			addPower = 15601,
			rate = 23,
			resNum = 1050000,
			speedUp = 0,
		},
		[19] = { 

			id = 19,
			labId = 41,
			buildLevel = 19,
			addPower = 22362,
			rate = 22,
			resNum = 1200000,
			speedUp = 0,
		},
		[20] = { 

			id = 20,
			labId = 41,
			buildLevel = 20,
			addPower = 31169,
			rate = 21,
			resNum = 1500000,
			speedUp = 0,
		},
		[21] = { 

			id = 21,
			labId = 41,
			buildLevel = 21,
			addPower = 43427,
			rate = 20,
			resNum = 1800000,
			speedUp = 0,
		},
		[22] = { 

			id = 22,
			labId = 41,
			buildLevel = 22,
			addPower = 59905,
			rate = 18,
			resNum = 2100000,
			speedUp = 0,
		},
		[23] = { 

			id = 23,
			labId = 41,
			buildLevel = 23,
			addPower = 82280,
			rate = 16,
			resNum = 2400000,
			speedUp = 0,
		},
		[24] = { 

			id = 24,
			labId = 41,
			buildLevel = 24,
			addPower = 111081,
			rate = 14,
			resNum = 2700000,
			speedUp = 0,
		},
		[25] = { 

			id = 25,
			labId = 41,
			buildLevel = 25,
			addPower = 148687,
			rate = 10,
			resNum = 3750000,
			speedUp = 100,
		},
}
Count=25
