--This file is generated by tools!
--Please do not modify this file!
module("tableData_tShowRule",package.seeall)
data = {


		[1001] = { 

			id = 1001,
			num = 10,
			prefab = "Pos_Army",
		},
		[1002] = { 

			id = 1002,
			num = 20,
			prefab = "Pos_Army_23",
		},
		[1003] = { 

			id = 1003,
			num = 20,
			prefab = "Pos_Army_23",
		},
		[1004] = { 

			id = 1004,
			num = 35,
			prefab = "Pos_Army_22",
		},
}
Count=4
