--This file is generated by tools!
--Please do not modify this file!
module("tableData_tCallUp",package.seeall)
data = {


		[1] = { 

			id = 1,
			labId = 5,
			buildLevel = 1,
			addPower = 8,
			number = 10,
			speed = 1,
		},
		[2] = { 

			id = 2,
			labId = 5,
			buildLevel = 2,
			addPower = 23,
			number = 15,
			speed = 1.5,
		},
		[3] = { 

			id = 3,
			labId = 5,
			buildLevel = 3,
			addPower = 41,
			number = 20,
			speed = 2,
		},
		[4] = { 

			id = 4,
			labId = 5,
			buildLevel = 4,
			addPower = 63,
			number = 30,
			speed = 2.5,
		},
		[5] = { 

			id = 5,
			labId = 5,
			buildLevel = 5,
			addPower = 91,
			number = 40,
			speed = 3,
		},
		[6] = { 

			id = 6,
			labId = 5,
			buildLevel = 6,
			addPower = 141,
			number = 50,
			speed = 3.5,
		},
		[7] = { 

			id = 7,
			labId = 5,
			buildLevel = 7,
			addPower = 193,
			number = 60,
			speed = 4,
		},
		[8] = { 

			id = 8,
			labId = 5,
			buildLevel = 8,
			addPower = 255,
			number = 70,
			speed = 4.5,
		},
		[9] = { 

			id = 9,
			labId = 5,
			buildLevel = 9,
			addPower = 353,
			number = 80,
			speed = 5,
		},
		[10] = { 

			id = 10,
			labId = 5,
			buildLevel = 10,
			addPower = 546,
			number = 90,
			speed = 6,
		},
		[11] = { 

			id = 11,
			labId = 5,
			buildLevel = 11,
			addPower = 881,
			number = 100,
			speed = 7,
		},
		[12] = { 

			id = 12,
			labId = 5,
			buildLevel = 12,
			addPower = 1305,
			number = 120,
			speed = 8,
		},
		[13] = { 

			id = 13,
			labId = 5,
			buildLevel = 13,
			addPower = 1965,
			number = 140,
			speed = 9,
		},
		[14] = { 

			id = 14,
			labId = 5,
			buildLevel = 14,
			addPower = 2969,
			number = 160,
			speed = 10,
		},
		[15] = { 

			id = 15,
			labId = 5,
			buildLevel = 15,
			addPower = 4529,
			number = 180,
			speed = 11,
		},
		[16] = { 

			id = 16,
			labId = 5,
			buildLevel = 16,
			addPower = 6937,
			number = 200,
			speed = 12,
		},
		[17] = { 

			id = 17,
			labId = 5,
			buildLevel = 17,
			addPower = 10566,
			number = 220,
			speed = 13,
		},
		[18] = { 

			id = 18,
			labId = 5,
			buildLevel = 18,
			addPower = 15601,
			number = 240,
			speed = 14,
		},
		[19] = { 

			id = 19,
			labId = 5,
			buildLevel = 19,
			addPower = 22362,
			number = 260,
			speed = 15,
		},
		[20] = { 

			id = 20,
			labId = 5,
			buildLevel = 20,
			addPower = 31169,
			number = 280,
			speed = 16,
		},
		[21] = { 

			id = 21,
			labId = 5,
			buildLevel = 21,
			addPower = 43427,
			number = 300,
			speed = 17,
		},
		[22] = { 

			id = 22,
			labId = 5,
			buildLevel = 22,
			addPower = 59905,
			number = 400,
			speed = 18,
		},
		[23] = { 

			id = 23,
			labId = 5,
			buildLevel = 23,
			addPower = 82280,
			number = 500,
			speed = 19,
		},
		[24] = { 

			id = 24,
			labId = 5,
			buildLevel = 24,
			addPower = 111081,
			number = 700,
			speed = 20,
		},
		[25] = { 

			id = 25,
			labId = 5,
			buildLevel = 25,
			addPower = 148687,
			number = 1000,
			speed = 25,
		},
}
Count=25
