--This file is generated by tools!
--Please do not modify this file!
module("tableData_tMobaTeam",package.seeall)
data = {


		[1] = { 

			id = 1,
			Name = "moba_mapzone1",
			Icon = "",
		},
		[2] = { 

			id = 2,
			Name = "moba_mapzone2",
			Icon = "",
		},
}
Count=2
