--This file is generated by tools!
--Please do not modify this file!
module("tableData_tStory",package.seeall)
data = {


		[1] = { 

			id = 1,
			TextId = "icon_guide_male:Chapterstory_01;icon_guide_male:Chapterstory_02;icon_guide12:Chapterstory_03;icon_guide_male:Chapterstory_04",
			Id1 = "bg_chap1",
			Id2 = "Activity_Grow_desc1",
		},
		[2] = { 

			id = 2,
			TextId = "icon_guide12:Chapterstory_11;icon_guide_male:Chapterstory_12;icon_guide11:Chapterstory_13;icon_guide11:Chapterstory_14;icon_guide_male:Chapterstory_15;icon_guide1:Chapterstory_16;icon_guide1:Chapterstory_17;icon_guide_male:Chapterstory_18",
			Id1 = "bg_chap2",
			Id2 = "Activity_Grow_desc2",
		},
		[3] = { 

			id = 3,
			TextId = "icon_guide12:Chapterstory_20;icon_guide_male:Chapterstory_21;icon_guide_male:Chapterstory_22;icon_guide9:Chapterstory_23",
			Id1 = "bg_chap3",
			Id2 = "Activity_Grow_desc3",
		},
		[4] = { 

			id = 4,
			TextId = "icon_guide12:Chapterstory_26;icon_guide_male:Chapterstory_27;icon_guide11:Chapterstory_28;icon_guide_male:Chapterstory_29",
			Id1 = "bg_chap4",
			Id2 = "Activity_Grow_desc4",
		},
		[5] = { 

			id = 5,
			TextId = "icon_guide11:Chapterstory_31;icon_guide1:Chapterstory_32;icon_guide_male:Chapterstory_33;icon_guide9:Chapterstory_34;icon_guide_male:Chapterstory_35",
			Id1 = "bg_chap5",
			Id2 = "Activity_Grow_desc5",
		},
		[6] = { 

			id = 6,
			TextId = "icon_guide:Chapterstory_39;icon_guide_male:Chapterstory_40",
			Id1 = "bg_chap6",
			Id2 = "Activity_Grow_desc6",
		},
		[7] = { 

			id = 7,
			TextId = "icon_guide12:Chapterstory_41;icon_guide9:Chapterstory_42;icon_guide9:Chapterstory_43;icon_guide_male:Chapterstory_44;icon_guide:Chapterstory_45;icon_guide_male:Chapterstory_46",
			Id1 = "bg_chap7",
			Id2 = "Activity_Grow_desc7",
		},
		[8] = { 

			id = 8,
			TextId = "icon_guide12:Chapterstory_49;icon_guide9:Chapterstory_50;icon_guide9:Chapterstory_51;icon_guide_male:Chapterstory_52",
			Id1 = "bg_chap8",
			Id2 = "Activity_Grow_desc8_1",
		},
		[9] = { 

			id = 9,
			TextId = "icon_guide9:Chapterstory_55;icon_guide:Chapterstory_56;icon_guide_male:Chapterstory_57",
			Id1 = "bg_chap8",
			Id2 = "Activity_Grow_desc9_1",
		},
		[10] = { 

			id = 10,
			TextId = "",
			Id1 = "bg_chap2",
			Id2 = "Activity_Grow_desc10",
		},
		[11] = { 

			id = 11,
			TextId = "",
			Id1 = "bg_chap4",
			Id2 = "Activity_Grow_desc11",
		},
		[12] = { 

			id = 12,
			TextId = "",
			Id1 = "bg_chap6",
			Id2 = "Activity_Grow_desc12",
		},
		[13] = { 

			id = 13,
			TextId = "",
			Id1 = "bg_chap8",
			Id2 = "Activity_Grow_desc13",
		},
		[101] = { 

			id = 101,
			TextId = "icon_guide12:Chapterstory_05;icon_guide_male:Chapterstory_06;icon_guide11:Chapterstory_07;icon_guide12:Chapterstory_08;203:Chapterstory_09;icon_guide_male:Chapterstory_10",
			Id1 = "",
			Id2 = "",
		},
		[102] = { 

			id = 102,
			TextId = "icon_guide_male:Chapterstory_19",
			Id1 = "",
			Id2 = "",
		},
		[103] = { 

			id = 103,
			TextId = "icon_guide_male:Chapterstory_24;305:Chapterstory_25",
			Id1 = "",
			Id2 = "",
		},
		[104] = { 

			id = 104,
			TextId = "icon_guide_male:Chapterstory_30",
			Id1 = "",
			Id2 = "",
		},
		[105] = { 

			id = 105,
			TextId = "icon_guide:Chapterstory_36;icon_guide9:Chapterstory_37;icon_guide_male:Chapterstory_38",
			Id1 = "",
			Id2 = "",
		},
		[106] = { 

			id = 106,
			TextId = "",
			Id1 = "",
			Id2 = "",
		},
		[107] = { 

			id = 107,
			TextId = "icon_guide_male:Chapterstory_47;icon_guide:Chapterstory_48",
			Id1 = "",
			Id2 = "",
		},
		[108] = { 

			id = 108,
			TextId = "icon_guide:Chapterstory_53;icon_guide_male:Chapterstory_54",
			Id1 = "",
			Id2 = "",
		},
		[109] = { 

			id = 109,
			TextId = "icon_guide:Chapterstory_58;icon_guide_male:Chapterstory_59",
			Id1 = "",
			Id2 = "",
		},
}
Count=22
