--This file is generated by tools!
--Please do not modify this file!
module("tableData_tUnionBadgeColor",package.seeall)
data = {


		[1] = { 

			id = 1,
			color = "ce222d",
			color2 = "FF0000",
		},
		[2] = { 

			id = 2,
			color = "7fc41c",
			color2 = "00FF00",
		},
		[3] = { 

			id = 3,
			color = "ffbf01",
			color2 = "FFFF00",
		},
		[4] = { 

			id = 4,
			color = "0b52a4",
			color2 = "0020FF",
		},
		[5] = { 

			id = 5,
			color = "82027b",
			color2 = "FF00FF",
		},
		[6] = { 

			id = 6,
			color = "01957d",
			color2 = "00FF5A",
		},
		[7] = { 

			id = 7,
			color = "ff8c00",
			color2 = "FF2D00",
		},
}
Count=7
